const fs = require('fs');
const path = require('path');
const dir = __dirname;
const words = JSON.parse(fs.readFileSync(path.join(dir,'spelling-reference.json'),'utf8'));

const defs = {
// A - simple
"a":["一个","one (article)"],
"add":["加","to put together"],
"ago":["以前","in the past"],
"all":["全部","every one"],
"am":["是","form of 'to be'"],
"an":["一个","one (before vowel)"],
"and":["和","also, with"],
"are":["是","form of 'to be'"],
"as":["像","like, the same way"],
"at":["在","in a place"],
"ate":["吃了","past tense of eat"],
"away":["离开","not here"],
// A - common
"able":["能够","can do something"],
"aboard":["上船","on a ship or plane"],
"about":["关于","on the topic of"],
"above":["上面","higher than"],
"actions":["行动","things you do"],
"actor":["演员","person in a movie"],
"adventure":["冒险","exciting journey"],
"after":["之后","later than"],
"again":["再次","one more time"],
"against":["对抗","opposite to"],
"air":["空气","what we breathe"],
"almost":["几乎","nearly"],
"along":["沿着","following a path"],
"also":["也","too, as well"],
"although":["虽然","even though"],
"always":["总是","every time"],
"animal":["动物","a living creature"],
"another":["另一个","one more"],
"any":["任何","no matter which"],
"anybody":["任何人","any person"],
"anyone":["任何人","any person at all"],
"anywhere":["任何地方","any place"],
"appear":["出现","to show up"],
"aren't":["不是","are not"],
"around":["周围","on all sides"],
"arrive":["到达","to get there"],
"asleep":["睡着","not awake"],
"attach":["附上","to join together"],
// A - difficult
"abandoned":["废弃的","left behind, empty"],
"absolutely":["绝对","completely, totally"],
"access":["进入","way to get in"],
"acknowledge":["承认","to say yes, it's true"],
"actually":["实际上","in fact, really"],
"adjusted":["调整了","changed to fit"],
"advantage":["优势","something that helps"],
"affect":["影响","to change something"],
"agencies":["机构","groups that help"],
"agreeable":["愉快的","nice, pleasant"],
"alien":["外星人","from another planet"],
"allergic":["过敏的","makes you sick"],
"amuse":["逗乐","to make someone laugh"],
"annual":["每年的","once a year"],
"answer":["回答","to reply"],
"area":["区域","a space or place"],
"assess":["评估","to check how good"],
"attachment":["附件","thing joined on"],
"attempt":["尝试","to try"],
"attention":["注意","looking and listening"],
"attractive":["漂亮的","nice to look at"],
"auction":["拍卖","selling to highest bid"],
"author":["作者","person who writes"],
"autograph":["签名","famous person's name"],
"awesome":["太棒了","really great"],
// A - challenging
"accelerating":["加速","going faster"],
"accidentally":["意外地","by mistake"],
"accommodation":["住宿","place to stay"],
"accumulate":["积累","to collect over time"],
"acquainted":["认识的","knowing someone"],
"acquire":["获得","to get"],
"adrenaline":["肾上腺素","excitement chemical"],
"aisle":["过道","path between seats"],
"annihilate":["消灭","to destroy completely"],
"annoyance":["烦恼","feeling bothered"],
"appearance":["外表","how you look"],
"appreciated":["感激的","thankful for"],
"appropriate":["合适的","right, proper"],
"archaeology":["考古学","study of old things"],
"awkwardly":["笨拙地","in a clumsy way"],
// B - simple
"bad":["坏的","not good"],
"bark":["叫","sound a dog makes"],
"bee":["蜜蜂","insect that makes honey"],
"bell":["铃","thing that rings"],
"best":["最好的","better than all"],
"big":["大的","not small"],
"bin":["垃圾桶","where rubbish goes"],
"bird":["鸟","animal with wings"],
"blow":["吹","push air out"],
"book":["书","pages to read"],
"box":["盒子","container"],
"bring":["带来","to carry here"],
"but":["但是","however"],
"by":["在旁边","near, next to"],
// B - common
"baby":["宝宝","very young child"],
"backyard":["后院","garden behind house"],
"bare":["光的","with nothing on"],
"beach":["海滩","sandy place by sea"],
"beaks":["鸟嘴","bird mouths"],
"because":["因为","for the reason that"],
"before":["之前","earlier than"],
"behave":["守规矩","act properly"],
"behind":["后面","at the back of"],
"being":["存在","living, existing"],
"belly":["肚子","tummy"],
"below":["下面","lower than"],
"between":["之间","in the middle of two"],
"bigger":["更大的","more big"],
"bike":["自行车","two-wheel ride"],
"birthday":["生日","day you were born"],
"bleed":["流血","lose blood"],
"blend":["混合","to mix together"],
"blind":["失明的","cannot see"],
"block":["积木","solid piece"],
"bodies":["身体","more than one body"],
"bottom":["底部","lowest part"],
"bought":["买了","past tense of buy"],
// B - difficult
"barely":["勉强","almost not"],
"beauty":["美丽","being pretty"],
"bounty":["赏金","reward"],
"beautiful":["美丽的","very pretty"],
"behaviours":["行为","ways of acting"],
"benefit":["好处","something good"],
"beware":["小心","watch out"],
"bough":["树枝","branch of a tree"],
"boulder":["巨石","very big rock"],
"boundary":["边界","edge, border"],
"breathless":["喘不过气","out of breath"],
"brethren":["兄弟们","brothers, group"],
"brief":["简短的","short, quick"],
"burglar":["小偷","person who steals"],
"business":["生意","work, company"],
// B - challenging
"baulk":["犹豫","to stop, refuse"],
"beige":["米色","light brown colour"],
"belligerence":["好斗","wanting to fight"],
"benefited":["受益了","was helped by"],
"benevolent":["仁慈的","kind, generous"],
"brevity":["简洁","being short and quick"],
"brilliance":["才华","great skill or light"],
"brusque":["粗鲁的","rude and quick"],
"buoy":["浮标","floating marker in water"],
// C - simple
"can":["能","to be able to"],
"car":["车","vehicle with wheels"],
"cheek":["脸颊","side of face"],
"clap":["拍手","hit hands together"],
"cow":["牛","farm animal, gives milk"],
"crab":["螃蟹","sea animal with claws"],
"crash":["撞击","to hit hard"],
"cup":["杯子","drink from it"],
// C - common
"cake":["蛋糕","sweet baked treat"],
"carries":["搬运","holds and moves"],
"catch":["抓住","to grab"],
"chain":["链条","metal links joined"],
"chalk":["粉笔","write on board with"],
"change":["改变","to make different"],
"chase":["追赶","to run after"],
"chest":["胸部","front of body"],
"child":["孩子","young person"],
"city":["城市","big town"],
"class":["班级","group of students"],
"claw":["爪子","sharp nail on animal"],
"clean":["干净的","not dirty"],
"climb":["攀爬","to go up"],
"clock":["时钟","tells the time"],
"close":["关闭","to shut"],
"colour":["颜色","red, blue, green etc."],
"contain":["包含","to hold inside"],
"cough":["咳嗽","push air from throat"],
"could":["能够","was able to"],
"couple":["一对","two together"],
"cracked":["裂开的","broken a little"],
"crime":["犯罪","breaking the law"],
"crowd":["人群","lots of people"],
// C - difficult
"calm":["平静的","quiet, peaceful"],
"carriage":["马车","wheeled vehicle"],
"category":["类别","group, type"],
"celebration":["庆祝","a party for something"],
"certain":["确定的","sure, definite"],
"character":["角色","person in a story"],
"cheques":["支票","paper to pay money"],
"chocolate":["巧克力","sweet brown treat"],
"circuit":["电路","path for electricity"],
"college":["大学","school after high school"],
"community":["社区","people living together"],
"competition":["比赛","contest to win"],
"complaining":["抱怨","saying you're unhappy"],
"complete":["完成","to finish"],
"concerned":["担心的","worried about"],
"confidence":["自信","believing in yourself"],
"consider":["考虑","to think about"],
"considerate":["体贴的","thinking of others"],
"continued":["继续了","kept going"],
"contraptions":["装置","strange machines"],
"convince":["说服","make someone agree"],
"coordinator":["协调员","person who organises"],
"corpses":["尸体","dead bodies"],
"creature":["生物","living thing"],
"crevice":["裂缝","narrow crack"],
"criminal":["罪犯","person who breaks law"],
"crystal":["水晶","clear shiny stone"],
"curious":["好奇的","wanting to know"],
// C - challenging
"camouflage":["伪装","hide by blending in"],
"carcasses":["尸体","dead animal bodies"],
"changeable":["多变的","likely to change"],
"climatic":["气候的","about the weather"],
"colloquial":["口语的","everyday speech"],
"colossal":["巨大的","extremely big"],
"column":["柱子","tall post or list"],
"competence":["能力","being able to do well"],
"complementary":["互补的","completing each other"],
"complimentary":["赞美的","saying nice things, free"],
"conscience":["良心","knowing right from wrong"],
"conscious":["有意识的","awake, aware"],
"consequently":["因此","as a result"],
"correspond":["通信","to write to each other"],
"courageous":["勇敢的","very brave"],
"cylinder":["圆柱体","tube shape"],
// D - simple
"day":["天","24 hours"],
"deep":["深的","far down"],
"did":["做了","past tense of do"],
"dog":["狗","pet that barks"],
"doll":["娃娃","toy person"],
"dot":["点","small round mark"],
"drag":["拖","to pull along"],
"dress":["裙子","clothing girls wear"],
"drip":["滴","water falling slowly"],
"drop":["掉落","to let fall"],
"drum":["鼓","hit to make music"],
// D - common
"dark":["黑暗的","no light"],
"dead":["死的","not alive"],
"destroy":["摧毁","to break completely"],
"detail":["细节","small part"],
"didn't":["没有","did not"],
"different":["不同的","not the same"],
"disarm":["解除武装","take weapons away"],
"discuss":["讨论","to talk about"],
"distance":["距离","how far away"],
"does":["做","form of 'do'"],
"doesn't":["不","does not"],
"don't":["不要","do not"],
"door":["门","opens to go through"],
"downstairs":["楼下","lower floor"],
"dragon":["龙","fire-breathing creature"],
"draw":["画","to make a picture"],
"dream":["梦","pictures while sleeping"],
"dry":["干的","not wet"],
"during":["期间","while something happens"],
// D - difficult
"damage":["损坏","to break or harm"],
"dangerous":["危险的","not safe"],
"decided":["决定了","made a choice"],
"decision":["决定","a choice"],
"decorate":["装饰","to make pretty"],
"defence":["防御","protection"],
"delicious":["美味的","tastes very good"],
"demolished":["拆毁了","knocked down"],
"demonstrate":["演示","to show how"],
"depot":["仓库","storage place"],
"depression":["抑郁","deep sadness"],
"deprived":["被剥夺的","taken away from"],
"deserts":["沙漠","dry sandy land"],
"dessert":["甜点","sweet food after meal"],
"designed":["设计了","planned and made"],
"detective":["侦探","person who solves crime"],
"digest":["消化","break down food"],
"disappear":["消失","to go away, vanish"],
"disappointed":["失望的","sad about result"],
"discover":["发现","to find something new"],
"drawer":["抽屉","sliding box in desk"],
"drought":["干旱","no rain for long time"],
"dye":["染料","colour for hair/cloth"],
// D - challenging
"debris":["碎片","broken pieces"],
"decomposed":["腐烂的","rotted away"],
"deficient":["不足的","not enough"],
"definitely":["肯定地","for sure"],
"dependency":["依赖","needing something"],
"desiccate":["干燥","to dry out completely"],
"desperate":["绝望的","needing help badly"],
"desperation":["绝望","feeling hopeless"],
"dominant":["占主导的","most powerful"],
"draught":["气流","cold air blowing in"],
"dungeon":["地牢","underground prison"],
// E - simple
"eat":["吃","to put food in mouth"],
"egg":["蛋","comes from a chicken"],
"end":["结束","the last part"],
"even":["甚至","also, flat"],
"ever":["曾经","at any time"],
// E - common
"earth":["地球","our planet"],
"enemy":["敌人","someone against you"],
"enjoy":["享受","to like doing"],
"enough":["足够","as much as needed"],
"every":["每个","all, each one"],
"everybody":["每个人","all people"],
"everyone":["每个人","all people"],
"everywhere":["到处","in all places"],
"evil":["邪恶的","very bad, wicked"],
"example":["例子","one to show others"],
"explain":["解释","to tell how or why"],
"eyes":["眼睛","you see with them"],
// E - difficult
"easiest":["最简单的","most easy"],
"echoed":["回响了","sound bounced back"],
"edible":["可食用的","safe to eat"],
"educational":["教育的","helps you learn"],
"eerie":["诡异的","strange and scary"],
"effect":["效果","result of something"],
"effective":["有效的","works well"],
"emerged":["出现了","came out"],
"endangered":["濒危的","might die out"],
"energy":["能量","power to do things"],
"engage":["参与","to join in"],
"engine":["引擎","machine that powers"],
"enjoyable":["愉快的","fun, pleasant"],
"enormous":["巨大的","very very big"],
"ensure":["确保","to make sure"],
"episode":["一集","one part of a show"],
"especially":["尤其","more than others"],
"esteem":["尊重","respect"],
"except":["除了","but not"],
"exciting":["令人兴奋的","makes you happy"],
"exclaimed":["惊叫","said with surprise"],
"exert":["施加","to use force"],
"expensive":["昂贵的","costs a lot"],
"experience":["经历","something that happened"],
"explosion":["爆炸","big bang"],
"extremely":["极其","very very much"],
// E - challenging
"effervescent":["冒泡的","bubbly, fizzy"],
"efficient":["高效的","works well, no waste"],
"embarrassed":["尴尬的","feeling shy or silly"],
"environment":["环境","world around us"],
"euphoric":["欣快的","extremely happy"],
"exaggerate":["夸张","make bigger than true"],
"exhilarating":["令人振奋","very exciting"],
"explanatory":["解释性的","helps explain"],
// F - simple
"fat":["胖的","not thin"],
"feel":["感觉","to touch or sense"],
"feet":["脚","at end of legs"],
"fell":["摔倒了","dropped down"],
"fill":["填满","to make full"],
"fit":["合适","right size"],
"five":["五","number 5"],
"food":["食物","what we eat"],
"for":["为了","meant for"],
"four":["四","number 4"],
"from":["从","coming out of"],
"fun":["乐趣","good time"],
// F - common
"face":["脸","front of head"],
"fair":["公平的","equal for all"],
"family":["家庭","parents and children"],
"fear":["害怕","feeling scared"],
"feather":["羽毛","bird's covering"],
"feelings":["感受","emotions inside"],
"fighting":["打架","hitting each other"],
"finally":["终于","at last"],
"fine":["好的","okay, good"],
"first":["第一","before all others"],
"flapping":["拍打","moving wings up/down"],
"flies":["飞","moves through air"],
"flight":["飞行","trip in the air"],
"floor":["地板","bottom of room"],
"flower":["花","pretty plant part"],
"fly":["飞","move through air"],
"followed":["跟随了","went after"],
"footsteps":["脚步","sounds of walking"],
"forest":["森林","lots of trees"],
"found":["找到了","discovered"],
"friend":["朋友","person you like"],
"fright":["惊吓","sudden fear"],
"fruit":["水果","apple, banana etc."],
"funny":["有趣的","makes you laugh"],
// F - difficult
"famous":["出名的","known by many people"],
"favourite":["最喜欢的","liked the most"],
"features":["特征","parts that stand out"],
"february":["二月","month after January"],
"fellowship":["友谊","friendship group"],
"fete":["游园会","outdoor fair, party"],
"fibre":["纤维","thin thread"],
"fiction":["小说","made-up story"],
"field":["田地","open grassy area"],
"fierce":["凶猛的","wild and scary"],
"formal":["正式的","proper, official"],
"formation":["形成","shape or arrangement"],
"fractures":["骨折","broken bones"],
"fragile":["脆弱的","easy to break"],
"frenzied":["疯狂的","wild and crazy"],
"frightened":["害怕的","feeling scared"],
"furniture":["家具","tables, chairs etc."],
"further":["更远","more far away"],
// F - challenging
"facilities":["设施","buildings to use"],
"fascinating":["迷人的","very interesting"],
"fluorescent":["荧光的","bright glowing colour"],
"fuchsia":["紫红色","pink-purple colour"],
"furnace":["熔炉","very hot oven"],
"futile":["徒劳的","useless, won't work"],
// G - simple
"get":["得到","to receive"],
"go":["去","to move somewhere"],
"going":["去","moving to a place"],
"good":["好的","not bad"],
"got":["得到了","past tense of get"],
"grass":["草","green ground plant"],
// G - common
"game":["游戏","something to play"],
"garden":["花园","place to grow plants"],
"gardening":["园艺","working in garden"],
"getting":["得到","receiving"],
"goes":["去","moves somewhere"],
"golden":["金色的","colour of gold"],
"goodness":["善良","being good"],
"globe":["地球仪","round model of earth"],
"great":["很棒的","very good"],
"green":["绿色","colour of grass"],
"ground":["地面","earth under feet"],
"group":["组","people together"],
// G - difficult
"galaxy":["银河","group of stars"],
"generation":["一代人","people born same time"],
"gesture":["手势","movement of hands"],
"gigantic":["巨大的","really really big"],
"glacier":["冰川","huge ice river"],
"global":["全球的","about the whole world"],
"gnawed":["啃了","chewed on"],
"goblet":["高脚杯","fancy drinking cup"],
"government":["政府","people who run country"],
"graphics":["图形","pictures on screen"],
"grumble":["抱怨","to complain quietly"],
"guess":["猜","to try to answer"],
// G - challenging
"gauge":["测量","to measure"],
"ghoul":["食尸鬼","scary ghost creature"],
"grandeur":["壮丽","great beauty, big"],
"guaranteed":["保证的","promised for sure"],
"guillotine":["断头台","cutting machine"],
"gynaecology":["妇科","women's health study"],
// H - simple
"hand":["手","at end of arm"],
"hard":["硬的","not soft, difficult"],
"has":["有","owns, possesses"],
"hat":["帽子","wear on head"],
"have":["有","to own"],
"he":["他","a boy or man"],
"help":["帮助","to assist"],
"her":["她的","belonging to a girl"],
"him":["他","a boy (object)"],
"hot":["热的","very warm"],
"how":["怎样","in what way"],
// H - common
"habit":["习惯","thing you always do"],
"hair":["头发","grows on head"],
"happen":["发生","to take place"],
"happiest":["最快乐的","most happy"],
"happy":["快乐的","feeling good"],
"hardly":["几乎不","almost not"],
"hatch":["孵化","come out of egg"],
"heaps":["很多","lots and lots"],
"hear":["听","use ears (not 'here')"],
"here":["这里","in this place (not 'hear')"],
"heard":["听到了","past tense of hear"],
"hearing":["听觉","using your ears"],
"heavier":["更重的","weighs more"],
"holidays":["假期","time off school"],
"home":["家","where you live"],
"hope":["希望","to wish for"],
"hoping":["希望着","wishing for"],
"hospital":["医院","where sick people go"],
"house":["房子","building to live in"],
"however":["然而","but, on other hand"],
"huge":["巨大的","very big"],
"humans":["人类","people"],
"hundred":["一百","number 100"],
"hunted":["猎杀了","chased to catch"],
// H - difficult
"hammock":["吊床","hanging bed"],
"haphazard":["杂乱的","messy, no plan"],
"haste":["匆忙","being in a rush"],
"haul":["拖","to pull hard"],
"healthy":["健康的","not sick"],
"heir":["继承人","person who gets next"],
"herd":["兽群","group of animals"],
"hesitated":["犹豫了","paused, unsure"],
"hilarious":["搞笑的","very very funny"],
"history":["历史","what happened before"],
"hoarse":["沙哑的","rough voice"],
"honest":["诚实的","tells the truth"],
"hopefully":["希望地","with hope"],
"horrified":["惊恐的","very very scared"],
"hostel":["旅社","cheap place to stay"],
"humorous":["幽默的","funny"],
"hurriedly":["匆忙地","in a rush"],
"hygiene":["卫生","keeping clean"],
// H - challenging
"haemoglobin":["血红蛋白","red part of blood"],
"hallucinate":["幻觉","see things not there"],
"helium":["氦气","gas that floats balloons"],
"hesitance":["犹豫","not being sure"],
"humanitarian":["人道主义","helping people"],
// I - simple
"i":["我","myself"],
"if":["如果","in case that"],
"in":["在里面","inside"],
"into":["进入","going inside"],
"is":["是","form of 'to be'"],
"it":["它","that thing"],
// I - common
"ice":["冰","frozen water"],
"idea":["想法","a thought"],
"important":["重要的","matters a lot"],
"insects":["昆虫","small bugs"],
"inside":["里面","in something"],
"invite":["邀请","ask to come"],
"islands":["岛屿","land in water"],
// I - difficult
"illegal":["非法的","against the law"],
"imagination":["想象力","making pictures in mind"],
"imaginative":["有想象力","good at thinking up"],
"implicate":["牵连","to involve in trouble"],
"impressed":["印象深刻","thought it was great"],
"improvement":["改善","getting better"],
"including":["包括","with, counting in"],
"inexpert":["不熟练的","not skilled"],
"information":["信息","facts, knowledge"],
"informative":["有启发的","teaches you things"],
"injury":["受伤","hurt to body"],
"insane":["疯狂的","crazy"],
"insolent":["无礼的","very rude"],
"instinct":["本能","natural feeling"],
"insurance":["保险","pay to protect"],
"intelligent":["聪明的","very smart"],
"intention":["意图","what you plan to do"],
"interesting":["有趣的","makes you curious"],
"interrupt":["打断","to stop someone talking"],
"invisible":["看不见的","can't be seen"],
"irrational":["不理性的","not making sense"],
"issue":["问题","a problem"],
// I - challenging
"imaginable":["可想象的","you can think of"],
"incandescent":["白炽的","glowing with heat"],
"incompetent":["无能的","not able to do well"],
"inconsequential":["无关紧要","not important"],
"inconsolable":["无法安慰","very very sad"],
"incorporate":["合并","to include, add in"],
"indecipherable":["难辨认","can't be read"],
"insanity":["疯狂","being crazy"],
"interrogate":["审问","to question hard"],
"intrigue":["阴谋","secret plan, interest"],
"intriguing":["有趣的","very interesting"],
"iridescent":["彩虹色","shiny rainbow colours"],
"irrelevant":["不相关的","doesn't matter"],
"irresponsible":["不负责的","not careful or wise"],
// J
"just":["刚刚","only, right now"],
"jacket":["夹克","short coat"],
"joke":["笑话","something funny"],
"juice":["果汁","drink from fruit"],
"jump":["跳","go up in the air"],
"jeopardy":["危险","in danger"],
"jettison":["抛弃","throw away"],
"journey":["旅程","a long trip"],
"jewels":["宝石","precious stones"],
"jewellery":["珠宝","rings and necklaces"],
"judicial":["司法的","about courts and law"],
// K
"keep":["保持","to hold on to"],
"kid":["小孩","a child"],
"key":["钥匙","opens a lock"],
"kitten":["小猫","baby cat"],
"knee":["膝盖","middle of leg"],
"knows":["知道","has knowledge"],
"kidnapped":["绑架了","taken by force"],
"kilometres":["公里","distance measure"],
"kiosk":["售货亭","small shop stand"],
"knowledge":["知识","what you know"],
"kaleidoscope":["万花筒","tube with patterns"],
"kayaking":["划皮艇","paddling a small boat"],
// L - simple
"land":["陆地","ground, earth"],
"lay":["放","to put down"],
"left":["左边","not right"],
"leg":["腿","walk with it"],
"lets":["让","allows"],
"lick":["舔","tongue touches"],
"like":["喜欢","to enjoy"],
"long":["长的","not short"],
"look":["看","to use eyes"],
"lot":["很多","many, a lot"],
// L - common
"ladies":["女士们","women"],
"lake":["湖","big body of water"],
"large":["大的","big"],
"laugh":["笑","happy sound"],
"laying":["放置","putting down"],
"leaf":["叶子","flat green on tree"],
"learn":["学习","to get knowledge"],
"leaves":["叶子","more than one leaf"],
"leaving":["离开","going away"],
"length":["长度","how long it is"],
"lesson":["课","time to learn"],
"letter":["信","written message"],
"lifelike":["逼真的","looks real"],
"light":["光","not dark"],
"limb":["肢","arm or leg"],
"little":["小的","not big"],
"live":["住","to be alive, stay"],
"living":["活着的","being alive"],
"local":["当地的","nearby"],
"loose":["松的","not tight"],
"lose":["丢失","to not have anymore"],
"loud":["大声的","not quiet"],
"love":["爱","care for deeply"],
// L - difficult
"language":["语言","words people speak"],
"lasers":["激光","strong light beams"],
"league":["联盟","group of teams"],
"library":["图书馆","place with books"],
"lightning":["闪电","light in a storm"],
"litany":["连祷","long boring list"],
"literacy":["读写能力","reading and writing"],
"lullaby":["摇篮曲","sleep song for baby"],
"lunar":["月球的","about the moon"],
"lyrebird":["琴鸟","bird that copies sounds"],
// L - challenging
"lacerate":["撕裂","to cut or tear"],
"leisure":["休闲","free time"],
"lieutenant":["中尉","army officer"],
"liquefy":["液化","turn into liquid"],
"litigious":["好打官司","likes to sue"],
"longevity":["长寿","living a long time"],
"luminescent":["发光的","giving off light"],
// M - simple
"may":["可以","is allowed to"],
"me":["我","myself (object)"],
"meet":["遇见","to come together"],
"men":["男人们","more than one man"],
"milk":["牛奶","white drink from cow"],
"much":["很多","a lot"],
"my":["我的","belongs to me"],
// M - common
"magazine":["杂志","thin book with pictures"],
"mainly":["主要地","mostly"],
"many":["很多","a large number"],
"mascot":["吉祥物","lucky character"],
"match":["比赛","game, contest"],
"meat":["肉","food from animals"],
"medals":["奖牌","prizes for winning"],
"medium":["中等的","in the middle size"],
"menu":["菜单","list of food choices"],
"merit":["优点","good quality"],
"messy":["脏乱的","not tidy"],
"metals":["金属","iron, gold etc."],
"might":["可能","maybe will"],
"migrate":["迁徙","move to new place"],
"modern":["现代的","new, up to date"],
"monday":["星期一","first day of week"],
"moonlight":["月光","light from moon"],
"moral":["道德","about right and wrong"],
"more":["更多","extra"],
"mother":["妈妈","female parent"],
"move":["移动","to go somewhere"],
"movie":["电影","film to watch"],
"muffled":["低沉的","quiet, hard to hear"],
"music":["音乐","songs and sounds"],
// M - difficult
"magic":["魔法","special power"],
"majestic":["雄伟的","grand, like a king"],
"malt":["麦芽","grain used in drinks"],
"martial":["武术的","about fighting"],
"massive":["巨大的","very very big"],
"matted":["缠结的","tangled together"],
"mayor":["市长","leader of a city"],
"measured":["测量了","found the size"],
"medicine":["药","helps when sick"],
"medieval":["中世纪的","from long ago"],
"minerals":["矿物","natural rocks"],
"molecule":["分子","tiny tiny piece"],
"molten":["熔化的","melted by heat"],
"moult":["换毛","lose old feathers"],
"mountain":["山","very tall land"],
"mucous":["黏液的","slimy (adjective)"],
"mucus":["黏液","slimy stuff in nose"],
"muscle":["肌肉","body part for moving"],
"muscular":["肌肉发达","strong body"],
"museum":["博物馆","place with old things"],
"mysterious":["神秘的","hard to explain"],
"mystery":["谜","something unknown"],
"mystic":["神秘的","magical, spiritual"],
"myth":["神话","old made-up story"],
// M - challenging
"magnificent":["壮丽的","wonderful, grand"],
"malaria":["疟疾","disease from mosquito"],
"mandible":["下颚","lower jaw bone"],
"manoeuvre":["操控","to move carefully"],
"mathematician":["数学家","maths expert"],
"mediaeval":["中世纪的","from the middle ages"],
"mesmerised":["着迷的","can't look away"],
"miniature":["微型的","very very small"],
"minions":["仆从","helpers, followers"],
"mischievous":["淘气的","naughty, playful"],
"misconstrue":["误解","to understand wrong"],
"misogyny":["厌女","dislike of women"],
// N - simple
"name":["名字","what you are called"],
"new":["新的","not old"],
"no":["不","opposite of yes"],
"not":["不","makes it negative"],
"nut":["坚果","hard-shell seed"],
// N - common
"native":["本地的","from that place"],
"naughty":["淘气的","badly behaved"],
"nearest":["最近的","closest"],
"necklace":["项链","jewellery for neck"],
"nectar":["花蜜","sweet flower juice"],
"nephew":["侄子","brother's son"],
"nice":["好的","pleasant, kind"],
"night":["夜晚","when it's dark"],
"noise":["噪音","loud sound"],
"noisy":["吵闹的","making lots of sound"],
"numb":["麻木的","can't feel anything"],
// N - difficult
"natural":["自然的","from nature"],
"negligent":["疏忽的","not careful enough"],
"neighbour":["邻居","person next door"],
"neither":["都不","not this one or that"],
"nervous":["紧张的","worried, anxious"],
"niece":["侄女","brother's daughter"],
"normality":["正常","being normal"],
"nutrition":["营养","food for health"],
"notice":["注意到","to see, spot"],
// N - challenging
"naivety":["天真","being too trusting"],
"narcissist":["自恋者","loves only themselves"],
"necessary":["必要的","must have"],
"nonchalant":["漫不经心","not worried at all"],
"noticeable":["显著的","easy to see"],
"notoriety":["臭名","being famous for bad"],
"nuisance":["讨厌鬼","annoying thing"],
// O - simple
"of":["的","belonging to"],
"old":["旧的","not new"],
"one":["一","number 1"],
"our":["我们的","belongs to us"],
"out":["外面","not inside"],
// O - common
"obtain":["获得","to get"],
"ocean":["海洋","big body of water"],
"octopus":["章鱼","8-arm sea animal"],
"off":["关","not on"],
"older":["更老的","more old"],
"once":["一次","one time"],
"onion":["洋葱","vegetable that makes cry"],
"oozing":["渗出","slowly leaking"],
"ordinary":["普通的","not special"],
"other":["其他的","not this one"],
"outback":["内陆","wild Australian land"],
"outdoors":["户外","outside"],
"outside":["外面","not inside"],
"over":["在上面","above"],
"own":["自己的","belonging to you"],
// O - difficult
"oblige":["帮忙","to do a favour"],
"observe":["观察","to watch carefully"],
"obviously":["显然","clearly, easy to see"],
"occur":["发生","to happen"],
"ogre":["食人魔","big scary monster"],
"omit":["省略","to leave out"],
"opportunity":["机会","a chance"],
"opposition":["反对","being against"],
"optical":["光学的","about eyes or light"],
"optimist":["乐观者","sees the good side"],
"option":["选项","a choice"],
"organise":["组织","to arrange, plan"],
"origami":["折纸","paper folding art"],
"orphan":["孤儿","child with no parents"],
"orphanage":["孤儿院","home for orphans"],
"oxygen":["氧气","gas we breathe"],
// O - challenging
"obedience":["服从","doing what you're told"],
"obnoxious":["讨厌的","very annoying"],
"obscure":["模糊的","hard to see or know"],
"observation":["观察","watching carefully"],
"obsessed":["着迷的","can't stop thinking"],
"obsessive":["强迫的","too focused on one thing"],
"occasionally":["偶尔","sometimes"],
"occasions":["场合","special times"],
"occurrence":["事件","something that happens"],
"opaque":["不透明的","can't see through"],
"oscillate":["振荡","swing back and forth"],
// P - simple
"park":["公园","place to play outside"],
"pay":["付钱","give money for"],
"pen":["笔","write with it"],
"play":["玩","have fun"],
"plot":["情节","story plan"],
"pull":["拉","drag toward you"],
"put":["放","place somewhere"],
// P - common
"pair":["一对","two together"],
"panic":["恐慌","sudden fear"],
"parents":["父母","mum and dad"],
"patter":["啪嗒声","light tapping sound"],
"paw":["爪子","animal's foot"],
"people":["人们","men, women, children"],
"perfect":["完美的","no mistakes"],
"phone":["电话","call people with it"],
"picture":["图片","image to look at"],
"pirate":["海盗","steals on the sea"],
"place":["地方","a spot, location"],
"planet":["星球","world in space"],
"plastic":["塑料","man-made material"],
"platform":["平台","raised flat area"],
"police":["警察","keep people safe"],
"poor":["穷的","not much money"],
"potatoes":["土豆","vegetable underground"],
"power":["力量","strength, energy"],
"pretty":["漂亮的","nice to look at"],
"princess":["公主","king's daughter"],
"problem":["问题","something to solve"],
"purpose":["目的","reason for doing"],
// P - difficult
"parallel":["平行的","same distance apart"],
"particular":["特定的","one specific thing"],
"pedestal":["底座","stand for statue"],
"personalities":["个性","how people act"],
"pincer":["钳子","claw for gripping"],
"plait":["辫子","braided hair"],
"pleasure":["快乐","happy feeling"],
"prankster":["恶作剧者","person who jokes"],
"pray":["祈祷","talk to God"],
"precious":["珍贵的","very valuable"],
"predators":["捕食者","animals that hunt"],
"presence":["存在","being there"],
"prey":["猎物","animal being hunted"],
"principal":["校长","head of school"],
"principle":["原则","rule or belief"],
"probably":["可能","most likely"],
"professor":["教授","university teacher"],
"pumpkin":["南瓜","big orange vegetable"],
"punctual":["准时的","on time"],
"pure":["纯的","clean, not mixed"],
"purest":["最纯的","most clean"],
"purist":["纯粹主义者","wants things perfect"],
"pursuit":["追求","chasing after"],
// P - challenging
"peculiar":["奇特的","strange, odd"],
"personally":["亲自","by yourself"],
"persuade":["说服","talk into doing"],
"persuasive":["有说服力","good at convincing"],
"pessimistic":["悲观的","expecting the worst"],
"phosphorescent":["磷光的","glows in the dark"],
"physically":["身体上","about the body"],
"plateau":["高原","flat high land"],
"population":["人口","number of people"],
"precise":["精确的","exact, correct"],
"prevalence":["普遍","how common it is"],
"privileged":["有特权的","having advantages"],
"proposition":["提议","an offer or idea"],
"psychiatrist":["精神科医生","mind doctor"],
"psychic":["通灵的","reads minds"],
"psychology":["心理学","study of the mind"],
// Q
"quality":["质量","how good it is"],
"queen":["女王","female ruler"],
"question":["问题","ask to find out"],
"quick":["快的","fast"],
"quickened":["加快了","got faster"],
"quickly":["快地","in a fast way"],
"quiet":["安静的","not loud"],
"quite":["相当","fairly, pretty much"],
"quaint":["古雅的","old and charming"],
"quay":["码头","place boats stop"],
"quench":["解渴","satisfy thirst"],
"query":["疑问","a question"],
"queue":["排队","line of people waiting"],
"quiescent":["静止的","still, not moving"],
// R - simple
"ran":["跑了","past tense of run"],
"red":["红色","colour of blood"],
"rest":["休息","to relax"],
"roof":["屋顶","top of building"],
"room":["房间","space in a house"],
"rot":["腐烂","to go bad"],
"run":["跑","to move fast"],
// R - common
"rain":["雨","water from sky"],
"rainbow":["彩虹","colourful arc in sky"],
"rainforest":["雨林","wet thick forest"],
"readers":["读者","people who read"],
"realise":["意识到","to understand"],
"really":["真的","truly"],
"recover":["恢复","to get better"],
"reflect":["反射","bounce light back"],
"region":["地区","area of land"],
"remember":["记住","not forget"],
"report":["报告","tell what happened"],
"reptile":["爬行动物","snake, lizard etc."],
"rescued":["救了","saved from danger"],
"results":["结果","what happened"],
"return":["返回","to come back"],
"revenge":["报仇","getting back at"],
"riot":["暴乱","angry crowd fight"],
"ripple":["涟漪","small wave"],
"roar":["吼叫","loud animal sound"],
"robot":["机器人","machine that works"],
"rodent":["啮齿动物","mouse, rat etc."],
"rude":["粗鲁的","not polite"],
"rumble":["隆隆声","low rolling sound"],
"running":["跑步","moving fast"],
// R - difficult
"radial":["辐射的","from the centre out"],
"ravine":["峡谷","deep narrow valley"],
"razor":["剃刀","sharp blade"],
"realistic":["现实的","like real life"],
"receive":["收到","to get something"],
"recent":["最近的","not long ago"],
"recognise":["认出","to know who it is"],
"recommend":["推荐","to suggest"],
"rectangular":["长方形的","rectangle shaped"],
"relationships":["关系","connections"],
"relevant":["相关的","matters, important"],
"reliving":["重温","living again"],
"reluctant":["不情愿的","don't want to"],
"remnant":["残余","leftover piece"],
"remorse":["悔恨","feeling very sorry"],
"replenish":["补充","fill up again"],
"require":["需要","to need"],
"resources":["资源","things you can use"],
"responsible":["负责的","in charge of"],
"rhyme":["押韵","words that sound same"],
"ridiculous":["荒谬的","very silly"],
"rogue":["流氓","dishonest person"],
// R - challenging
"racquet":["球拍","bat for tennis"],
"rancour":["怨恨","deep anger"],
"realistically":["现实地","in a real way"],
"recognisable":["可识别的","easy to know"],
"redemption":["救赎","being saved"],
"reign":["统治","rule as king/queen"],
"rein":["缰绳","strap to control horse"],
"reminiscent":["令人想起","makes you remember"],
"responsibility":["责任","duty to do"],
"resurrect":["复活","bring back to life"],
"resuscitate":["复苏","bring back breathing"],
"rhythm":["节奏","musical beat"],
"ricochet":["弹跳","bounce off something"],
"rigorous":["严格的","very strict"],
// S - simple
"sad":["伤心的","not happy"],
"saw":["看到了","past tense of see"],
"say":["说","to speak words"],
"see":["看","use your eyes"],
"seed":["种子","plant grows from it"],
"seem":["似乎","looks like"],
"set":["放置","to put in place"],
"she":["她","a girl or woman"],
"shed":["棚子","small garden building"],
"shop":["商店","place to buy things"],
"shut":["关","to close"],
"sing":["唱","make music with voice"],
"sit":["坐","rest on a chair"],
"six":["六","number 6"],
"slow":["慢的","not fast"],
"so":["所以","therefore"],
"spot":["地点","a place, a dot"],
"stand":["站","be on your feet"],
"sleep":["睡觉","rest with eyes closed"],
// S - common
"safety":["安全","being safe"],
"said":["说了","past tense of say"],
"saving":["储蓄","keeping money"],
"says":["说","speaks"],
"scare":["吓","to frighten"],
"scatter":["散开","spread everywhere"],
"school":["学校","where you learn"],
"science":["科学","study of how things work"],
"scorch":["烧焦","burn a little"],
"scrape":["刮","rub against hard"],
"scream":["尖叫","shout very loud"],
"second":["第二","after first"],
"secret":["秘密","hidden thing"],
"several":["几个","more than two"],
"shaking":["发抖","moving back and forth"],
"shape":["形状","circle, square etc."],
"sharp":["锋利的","can cut"],
"shiny":["闪亮的","reflects light"],
"shock":["震惊","big surprise"],
"should":["应该","ought to"],
"shout":["喊","call out loud"],
"show":["展示","let others see"],
"sign":["标志","tells you something"],
"sitting":["坐着","resting on chair"],
"sixth":["第六","after fifth"],
"size":["大小","how big it is"],
"sky":["天空","above us, blue"],
"small":["小的","not big"],
"someone":["某人","a person"],
"sorts":["种类","different types"],
"sound":["声音","what you hear"],
"speak":["说话","to talk"],
"speech":["演讲","talk to people"],
"sprawl":["蔓延","spread out wide"],
"station":["车站","where trains stop"],
"steal":["偷","take without asking"],
"stepped":["踩了","put foot down"],
"stopped":["停了","did not continue"],
"strange":["奇怪的","weird, unusual"],
"strip":["条","thin piece"],
"strong":["强壮的","lots of power"],
"structure":["结构","how it's built"],
"strung":["串了","put on a string"],
"such":["这样的","of that kind"],
"suddenly":["突然","without warning"],
"surprise":["惊喜","not expected"],
"swimming":["游泳","moving in water"],
// S - difficult
"sapphire":["蓝宝石","blue precious stone"],
"saxophone":["萨克斯","music instrument"],
"scavenger":["食腐动物","finds and eats scraps"],
"scene":["场景","part of a play"],
"sceptical":["怀疑的","not sure it's true"],
"schnitzel":["炸肉排","fried meat slice"],
"scientific":["科学的","about science"],
"scissors":["剪刀","cut paper with"],
"seize":["抓住","grab quickly"],
"sewage":["污水","dirty water waste"],
"sewerage":["下水道","pipes for waste water"],
"shoulder":["肩膀","top of arm"],
"shrieked":["尖叫了","screamed high"],
"signal":["信号","sign or message"],
"skeleton":["骨架","all the bones"],
"slaughter":["屠杀","to kill many"],
"society":["社会","people living together"],
"sought":["寻找了","looked for"],
"spectacular":["壮观的","amazing to see"],
"stammered":["结巴了","spoke with difficulty"],
"stomach":["胃","where food goes"],
"submarine":["潜水艇","boat under water"],
"subsided":["平息了","calmed down"],
"success":["成功","doing well"],
"suitable":["合适的","right for the job"],
"summoned":["召唤了","called to come"],
"supervision":["监督","watching over"],
"surrounded":["围绕了","all around"],
"survive":["生存","stay alive"],
"system":["系统","set of parts working"],
// S - challenging
"sabotage":["破坏","damage on purpose"],
"scimitar":["弯刀","curved sword"],
"scintillate":["闪烁","to sparkle"],
"separate":["分开的","not together"],
"silhouette":["剪影","dark shape outline"],
"skulduggery":["阴谋","secret dishonest acts"],
"sovereign":["君主","king or queen"],
"stationary":["静止的","not moving"],
"stationery":["文具","pens, paper (not moving)"],
"sufficient":["足够的","enough"],
// T - simple
"teeth":["牙齿","in your mouth, bite"],
"tell":["告诉","say to someone"],
"tells":["告诉","says to someone"],
"ten":["十","number 10"],
"that":["那个","the one there"],
"the":["这/那","points to something"],
"then":["然后","after that"],
"thing":["东西","an object"],
"this":["这个","the one here"],
"to":["到","toward"],
"today":["今天","this day"],
"top":["顶部","highest part"],
// T - common
"table":["桌子","flat surface, legs"],
"tail":["尾巴","back end of animal"],
"tall":["高的","not short"],
"teacher":["老师","person who teaches"],
"team":["队","group working together"],
"their":["他们的","belongs to them (people)"],
"there":["那里","in that place (not their)"],
"they":["他们","those people"],
"they're":["他们是","they are"],
"though":["虽然","even if"],
"thought":["想法","idea in your mind"],
"title":["标题","name of book/movie"],
"together":["一起","with each other"],
"tomorrow":["明天","the next day"],
"too":["也","as well, also"],
"two":["二","number 2"],
"touched":["摸了","felt with hand"],
"tower":["塔","tall building"],
"train":["火车","rides on tracks"],
"travel":["旅行","go on a trip"],
"treat":["对待","act toward, a gift"],
"trick":["把戏","clever plan"],
"tries":["尝试","works hard to do"],
"trouble":["麻烦","problem, difficulty"],
// T - difficult
"taffeta":["塔夫绸","shiny smooth cloth"],
"talons":["利爪","bird's sharp claws"],
"tarantula":["狼蛛","big hairy spider"],
"taught":["教了","past tense of teach"],
"technique":["技巧","way of doing"],
"temperature":["温度","how hot or cold"],
"tension":["紧张","stress, tightness"],
"tentacles":["触手","long arms of octopus"],
"terrace":["露台","outdoor flat area"],
"terrible":["糟糕的","very bad"],
"terribly":["非常","very badly"],
"terrified":["恐惧的","very scared"],
"territory":["领地","area of land owned"],
"thermonuclear":["热核的","very powerful energy"],
"transfixed":["呆住了","can't move, staring"],
"travelled":["旅行了","went on a trip"],
"treasure":["宝藏","valuable things"],
// T - challenging
"telekinesis":["心灵感应","moving things with mind"],
"temperamental":["喜怒无常","mood changes a lot"],
"temporary":["临时的","for a short time"],
"therapeutic":["治疗的","helps you heal"],
"thoroughly":["彻底地","completely"],
"tournament":["锦标赛","competition event"],
"tsunami":["海啸","giant ocean wave"],
// U - simple
"undo":["撤销","reverse what was done"],
"up":["上","toward the sky"],
// U - common
"ugly":["丑的","not nice to look at"],
"uncle":["叔叔","parent's brother"],
"underneath":["下面","below"],
"understand":["理解","to get it"],
"until":["直到","up to the time"],
"use":["使用","to work with"],
"used":["用了","worked with"],
"useful":["有用的","helpful"],
"using":["使用","working with"],
"usually":["通常","most of the time"],
// U - difficult
"unbelievable":["难以置信","hard to believe"],
"uncomfortable":["不舒服的","not cosy"],
"unexpectedly":["出乎意料","by surprise"],
"unfortunately":["不幸地","sadly"],
"unique":["独特的","one of a kind"],
"unnatural":["不自然的","not normal"],
"upholsterer":["装潢师","fixes furniture cover"],
"urban":["城市的","about the city"],
"urgency":["紧迫","needing it now"],
"useless":["没用的","not helpful"],
// U - challenging
"ubiquitous":["无处不在","everywhere"],
"unconscious":["昏迷的","not awake"],
"unnecessary":["不必要的","not needed"],
// V - simple
"vat":["大桶","big container"],
"vet":["兽医","animal doctor"],
// V - common
"vanish":["消失","to disappear"],
"very":["非常","a lot"],
"view":["景色","what you can see"],
"vomit":["呕吐","throw up"],
// V - difficult
"valuable":["有价值的","worth a lot"],
"vegetation":["植被","plants and trees"],
"verdant":["翠绿的","green with plants"],
"vessel":["船","large boat"],
"victory":["胜利","winning"],
"villages":["村庄","small towns"],
"violence":["暴力","hurting people"],
"vision":["视力","ability to see"],
"voyage":["航行","long sea trip"],
"vortex":["漩涡","spinning circle"],
"vultures":["秃鹫","birds that eat dead"],
// V - challenging
"vertebrates":["脊椎动物","animals with backbone"],
"vicious":["凶恶的","mean and cruel"],
"vulnerable":["脆弱的","easy to hurt"],
// W - simple
"was":["是","past of 'is'"],
"we":["我们","us together"],
"well":["好","in a good way"],
"went":["去了","past tense of go"],
"will":["将","going to"],
"wish":["希望","want something"],
"with":["和","together, using"],
// W - common
"wait":["等","stay until ready"],
"walks":["走路","moves on feet"],
"wall":["墙","side of a room"],
"want":["想要","wish to have"],
"war":["战争","countries fighting"],
"warn":["警告","tell about danger"],
"watch":["看","to look at carefully"],
"water":["水","clear liquid to drink"],
"wear":["穿","put clothes on"],
"webbed":["有蹼的","toes joined by skin"],
"welcome":["欢迎","glad you came"],
"were":["是","past of 'are'"],
"what":["什么","asking about thing"],
"when":["什么时候","at what time"],
"where":["哪里","at what place"],
"which":["哪个","what one"],
"white":["白色","colour of snow"],
"who":["谁","what person"],
"whole":["整个","all of it"],
"whose":["谁的","belonging to whom"],
"window":["窗户","glass in wall"],
"wings":["翅膀","birds fly with them"],
"winning":["赢","getting the prize"],
"witch":["女巫","magic woman"],
"without":["没有","not having"],
"wizard":["巫师","magic man"],
"woke":["醒了","stopped sleeping"],
"woman":["女人","adult female"],
"world":["世界","the whole earth"],
"worried":["担心的","feeling anxious"],
"would":["会","past of 'will'"],
"wouldn't":["不会","would not"],
"write":["写","put words on paper"],
"writing":["写作","putting words down"],
"wrong":["错的","not right"],
// W - difficult
"wary":["警惕的","being careful"],
"wealthy":["富有的","having lots of money"],
"weary":["疲倦的","very tired"],
"wearisome":["令人厌烦","boring, tiring"],
"weighed":["称了","measured weight"],
"weight":["重量","how heavy"],
"weird":["奇怪的","strange"],
"whisper":["低语","speak very softly"],
"wholly":["完全地","all, completely"],
"witchery":["巫术","magic spells"],
"women":["女人们","more than one woman"],
"wonder":["想知道","think about"],
"wonderful":["极好的","very very good"],
"wrapped":["包裹了","covered up"],
"wrinkle":["皱纹","line on skin"],
"written":["写好的","put in writing"],
// W - challenging
"waive":["放弃","give up a right"],
"wilful":["故意的","done on purpose"],
"wondrous":["奇妙的","amazing, wonderful"],
"wraith":["幽灵","ghost"],
"wrought":["锻造的","made carefully"],
// X
"x-ray":["X光","see inside body"],
// Y - simple
"yell":["大叫","shout loudly"],
"yes":["是的","opposite of no"],
"you":["你","the person spoken to"],
// Y - common
"yelled":["大叫了","shouted loudly"],
"yellow":["黄色","colour of banana"],
"yoke":["轭","frame on animal's neck"],
"your":["你的","belongs to you"],
"yourself":["你自己","you alone"],
// Y - difficult
"yacht":["游艇","big fancy boat"],
"yearn":["渴望","want very much"],
"yield":["屈服","to give in"],
"youngster":["年轻人","young person"],
"youthful":["年轻的","looking young"],
// Z
"zoo":["动物园","place to see animals"],
"zapped":["击中了","hit with energy"],
"zany":["滑稽的","funny and silly"],
"zenith":["顶点","highest point"],
"zodiac":["星座","star signs"],
"zoology":["动物学","study of animals"],
"zephyr":["微风","gentle breeze"],
};

// Build output
const items = words.map(w => {
  const d = defs[w.word];
  if (!d) {
    console.error('MISSING:', w.word);
    return null;
  }
  const esc = s => s.replace(/\\/g,'\\\\').replace(/"/g,'\\"');
  return `{w:"${esc(w.word)}",m:"${esc(d[0])}",e:"${esc(d[1])}",l:"${w.level}",lt:"${w.letter}"}`;
});

const missing = items.filter(x => x === null).length;
if (missing > 0) {
  console.error(`${missing} words missing definitions!`);
}

const valid = items.filter(x => x !== null);
const out = `const VOCAB = [\n${valid.join(',\n')}\n];\n`;
fs.writeFileSync(path.join(dir,'vocab.js'), out, 'utf8');
console.log(`Done! ${valid.length} words written to vocab.js`);
