const VOCAB = [
{w:"a",m:"一个",e:"one (article)",l:"simple",lt:"A"},
{w:"add",m:"加",e:"to put together",l:"simple",lt:"A"},
{w:"ago",m:"以前",e:"in the past",l:"simple",lt:"A"},
{w:"all",m:"全部",e:"every one",l:"simple",lt:"A"},
{w:"am",m:"是",e:"form of 'to be'",l:"simple",lt:"A"},
{w:"an",m:"一个",e:"one (before vowel)",l:"simple",lt:"A"},
{w:"and",m:"和",e:"also, with",l:"simple",lt:"A"},
{w:"are",m:"是",e:"form of 'to be'",l:"simple",lt:"A"},
{w:"as",m:"像",e:"like, the same way",l:"simple",lt:"A"},
{w:"at",m:"在",e:"in a place",l:"simple",lt:"A"},
{w:"ate",m:"吃了",e:"past tense of eat",l:"simple",lt:"A"},
{w:"away",m:"离开",e:"not here",l:"simple",lt:"A"},
{w:"able",m:"能够",e:"can do something",l:"common",lt:"A"},
{w:"aboard",m:"上船",e:"on a ship or plane",l:"common",lt:"A"},
{w:"about",m:"关于",e:"on the topic of",l:"common",lt:"A"},
{w:"above",m:"上面",e:"higher than",l:"common",lt:"A"},
{w:"actions",m:"行动",e:"things you do",l:"common",lt:"A"},
{w:"actor",m:"演员",e:"person in a movie",l:"common",lt:"A"},
{w:"adventure",m:"冒险",e:"exciting journey",l:"common",lt:"A"},
{w:"after",m:"之后",e:"later than",l:"common",lt:"A"},
{w:"again",m:"再次",e:"one more time",l:"common",lt:"A"},
{w:"against",m:"对抗",e:"opposite to",l:"common",lt:"A"},
{w:"air",m:"空气",e:"what we breathe",l:"common",lt:"A"},
{w:"almost",m:"几乎",e:"nearly",l:"common",lt:"A"},
{w:"along",m:"沿着",e:"following a path",l:"common",lt:"A"},
{w:"also",m:"也",e:"too, as well",l:"common",lt:"A"},
{w:"although",m:"虽然",e:"even though",l:"common",lt:"A"},
{w:"always",m:"总是",e:"every time",l:"common",lt:"A"},
{w:"animal",m:"动物",e:"a living creature",l:"common",lt:"A"},
{w:"another",m:"另一个",e:"one more",l:"common",lt:"A"},
{w:"any",m:"任何",e:"no matter which",l:"common",lt:"A"},
{w:"anybody",m:"任何人",e:"any person",l:"common",lt:"A"},
{w:"anyone",m:"任何人",e:"any person at all",l:"common",lt:"A"},
{w:"anywhere",m:"任何地方",e:"any place",l:"common",lt:"A"},
{w:"appear",m:"出现",e:"to show up",l:"common",lt:"A"},
{w:"aren't",m:"不是",e:"are not",l:"common",lt:"A"},
{w:"around",m:"周围",e:"on all sides",l:"common",lt:"A"},
{w:"arrive",m:"到达",e:"to get there",l:"common",lt:"A"},
{w:"asleep",m:"睡着",e:"not awake",l:"common",lt:"A"},
{w:"attach",m:"附上",e:"to join together",l:"common",lt:"A"},
{w:"abandoned",m:"废弃的",e:"left behind, empty",l:"difficult",lt:"A"},
{w:"absolutely",m:"绝对",e:"completely, totally",l:"difficult",lt:"A"},
{w:"access",m:"进入",e:"way to get in",l:"difficult",lt:"A"},
{w:"acknowledge",m:"承认",e:"to say yes, it's true",l:"difficult",lt:"A"},
{w:"actually",m:"实际上",e:"in fact, really",l:"difficult",lt:"A"},
{w:"adjusted",m:"调整了",e:"changed to fit",l:"difficult",lt:"A"},
{w:"advantage",m:"优势",e:"something that helps",l:"difficult",lt:"A"},
{w:"affect",m:"影响",e:"to change something",l:"difficult",lt:"A"},
{w:"agencies",m:"机构",e:"groups that help",l:"difficult",lt:"A"},
{w:"agreeable",m:"愉快的",e:"nice, pleasant",l:"difficult",lt:"A"},
{w:"alien",m:"外星人",e:"from another planet",l:"difficult",lt:"A"},
{w:"allergic",m:"过敏的",e:"makes you sick",l:"difficult",lt:"A"},
{w:"amuse",m:"逗乐",e:"to make someone laugh",l:"difficult",lt:"A"},
{w:"annual",m:"每年的",e:"once a year",l:"difficult",lt:"A"},
{w:"answer",m:"回答",e:"to reply",l:"difficult",lt:"A"},
{w:"area",m:"区域",e:"a space or place",l:"difficult",lt:"A"},
{w:"assess",m:"评估",e:"to check how good",l:"difficult",lt:"A"},
{w:"attachment",m:"附件",e:"thing joined on",l:"difficult",lt:"A"},
{w:"attempt",m:"尝试",e:"to try",l:"difficult",lt:"A"},
{w:"attention",m:"注意",e:"looking and listening",l:"difficult",lt:"A"},
{w:"attractive",m:"漂亮的",e:"nice to look at",l:"difficult",lt:"A"},
{w:"auction",m:"拍卖",e:"selling to highest bid",l:"difficult",lt:"A"},
{w:"author",m:"作者",e:"person who writes",l:"difficult",lt:"A"},
{w:"autograph",m:"签名",e:"famous person's name",l:"difficult",lt:"A"},
{w:"awesome",m:"太棒了",e:"really great",l:"difficult",lt:"A"},
{w:"accelerating",m:"加速",e:"going faster",l:"challenging",lt:"A"},
{w:"accidentally",m:"意外地",e:"by mistake",l:"challenging",lt:"A"},
{w:"accommodation",m:"住宿",e:"place to stay",l:"challenging",lt:"A"},
{w:"accumulate",m:"积累",e:"to collect over time",l:"challenging",lt:"A"},
{w:"acquainted",m:"认识的",e:"knowing someone",l:"challenging",lt:"A"},
{w:"acquire",m:"获得",e:"to get",l:"challenging",lt:"A"},
{w:"adrenaline",m:"肾上腺素",e:"excitement chemical",l:"challenging",lt:"A"},
{w:"aisle",m:"过道",e:"path between seats",l:"challenging",lt:"A"},
{w:"annihilate",m:"消灭",e:"to destroy completely",l:"challenging",lt:"A"},
{w:"annoyance",m:"烦恼",e:"feeling bothered",l:"challenging",lt:"A"},
{w:"appearance",m:"外表",e:"how you look",l:"challenging",lt:"A"},
{w:"appreciated",m:"感激的",e:"thankful for",l:"challenging",lt:"A"},
{w:"appropriate",m:"合适的",e:"right, proper",l:"challenging",lt:"A"},
{w:"archaeology",m:"考古学",e:"study of old things",l:"challenging",lt:"A"},
{w:"awkwardly",m:"笨拙地",e:"in a clumsy way",l:"challenging",lt:"A"},
{w:"bad",m:"坏的",e:"not good",l:"simple",lt:"B"},
{w:"bark",m:"叫",e:"sound a dog makes",l:"simple",lt:"B"},
{w:"bee",m:"蜜蜂",e:"insect that makes honey",l:"simple",lt:"B"},
{w:"bell",m:"铃",e:"thing that rings",l:"simple",lt:"B"},
{w:"best",m:"最好的",e:"better than all",l:"simple",lt:"B"},
{w:"big",m:"大的",e:"not small",l:"simple",lt:"B"},
{w:"bin",m:"垃圾桶",e:"where rubbish goes",l:"simple",lt:"B"},
{w:"bird",m:"鸟",e:"animal with wings",l:"simple",lt:"B"},
{w:"blow",m:"吹",e:"push air out",l:"simple",lt:"B"},
{w:"book",m:"书",e:"pages to read",l:"simple",lt:"B"},
{w:"box",m:"盒子",e:"container",l:"simple",lt:"B"},
{w:"bring",m:"带来",e:"to carry here",l:"simple",lt:"B"},
{w:"but",m:"但是",e:"however",l:"simple",lt:"B"},
{w:"by",m:"在旁边",e:"near, next to",l:"simple",lt:"B"},
{w:"baby",m:"宝宝",e:"very young child",l:"common",lt:"B"},
{w:"backyard",m:"后院",e:"garden behind house",l:"common",lt:"B"},
{w:"bare",m:"光的",e:"with nothing on",l:"common",lt:"B"},
{w:"beach",m:"海滩",e:"sandy place by sea",l:"common",lt:"B"},
{w:"beaks",m:"鸟嘴",e:"bird mouths",l:"common",lt:"B"},
{w:"because",m:"因为",e:"for the reason that",l:"common",lt:"B"},
{w:"before",m:"之前",e:"earlier than",l:"common",lt:"B"},
{w:"behave",m:"守规矩",e:"act properly",l:"common",lt:"B"},
{w:"behind",m:"后面",e:"at the back of",l:"common",lt:"B"},
{w:"being",m:"存在",e:"living, existing",l:"common",lt:"B"},
{w:"belly",m:"肚子",e:"tummy",l:"common",lt:"B"},
{w:"below",m:"下面",e:"lower than",l:"common",lt:"B"},
{w:"between",m:"之间",e:"in the middle of two",l:"common",lt:"B"},
{w:"bigger",m:"更大的",e:"more big",l:"common",lt:"B"},
{w:"bike",m:"自行车",e:"two-wheel ride",l:"common",lt:"B"},
{w:"birthday",m:"生日",e:"day you were born",l:"common",lt:"B"},
{w:"bleed",m:"流血",e:"lose blood",l:"common",lt:"B"},
{w:"blend",m:"混合",e:"to mix together",l:"common",lt:"B"},
{w:"blind",m:"失明的",e:"cannot see",l:"common",lt:"B"},
{w:"block",m:"积木",e:"solid piece",l:"common",lt:"B"},
{w:"bodies",m:"身体",e:"more than one body",l:"common",lt:"B"},
{w:"bottom",m:"底部",e:"lowest part",l:"common",lt:"B"},
{w:"bought",m:"买了",e:"past tense of buy",l:"common",lt:"B"},
{w:"barely",m:"勉强",e:"almost not",l:"difficult",lt:"B"},
{w:"beauty",m:"美丽",e:"being pretty",l:"difficult",lt:"B"},
{w:"bounty",m:"赏金",e:"reward",l:"difficult",lt:"B"},
{w:"beautiful",m:"美丽的",e:"very pretty",l:"difficult",lt:"B"},
{w:"behaviours",m:"行为",e:"ways of acting",l:"difficult",lt:"B"},
{w:"benefit",m:"好处",e:"something good",l:"difficult",lt:"B"},
{w:"beware",m:"小心",e:"watch out",l:"difficult",lt:"B"},
{w:"bough",m:"树枝",e:"branch of a tree",l:"difficult",lt:"B"},
{w:"boulder",m:"巨石",e:"very big rock",l:"difficult",lt:"B"},
{w:"boundary",m:"边界",e:"edge, border",l:"difficult",lt:"B"},
{w:"breathless",m:"喘不过气",e:"out of breath",l:"difficult",lt:"B"},
{w:"brethren",m:"兄弟们",e:"brothers, group",l:"difficult",lt:"B"},
{w:"brief",m:"简短的",e:"short, quick",l:"difficult",lt:"B"},
{w:"burglar",m:"小偷",e:"person who steals",l:"difficult",lt:"B"},
{w:"business",m:"生意",e:"work, company",l:"difficult",lt:"B"},
{w:"baulk",m:"犹豫",e:"to stop, refuse",l:"challenging",lt:"B"},
{w:"beige",m:"米色",e:"light brown colour",l:"challenging",lt:"B"},
{w:"belligerence",m:"好斗",e:"wanting to fight",l:"challenging",lt:"B"},
{w:"benefited",m:"受益了",e:"was helped by",l:"challenging",lt:"B"},
{w:"benevolent",m:"仁慈的",e:"kind, generous",l:"challenging",lt:"B"},
{w:"brevity",m:"简洁",e:"being short and quick",l:"challenging",lt:"B"},
{w:"brilliance",m:"才华",e:"great skill or light",l:"challenging",lt:"B"},
{w:"brusque",m:"粗鲁的",e:"rude and quick",l:"challenging",lt:"B"},
{w:"buoy",m:"浮标",e:"floating marker in water",l:"challenging",lt:"B"},
{w:"can",m:"能",e:"to be able to",l:"simple",lt:"C"},
{w:"car",m:"车",e:"vehicle with wheels",l:"simple",lt:"C"},
{w:"cheek",m:"脸颊",e:"side of face",l:"simple",lt:"C"},
{w:"clap",m:"拍手",e:"hit hands together",l:"simple",lt:"C"},
{w:"cow",m:"牛",e:"farm animal, gives milk",l:"simple",lt:"C"},
{w:"crab",m:"螃蟹",e:"sea animal with claws",l:"simple",lt:"C"},
{w:"crash",m:"撞击",e:"to hit hard",l:"simple",lt:"C"},
{w:"cup",m:"杯子",e:"drink from it",l:"simple",lt:"C"},
{w:"cake",m:"蛋糕",e:"sweet baked treat",l:"common",lt:"C"},
{w:"carries",m:"搬运",e:"holds and moves",l:"common",lt:"C"},
{w:"catch",m:"抓住",e:"to grab",l:"common",lt:"C"},
{w:"chain",m:"链条",e:"metal links joined",l:"common",lt:"C"},
{w:"chalk",m:"粉笔",e:"write on board with",l:"common",lt:"C"},
{w:"change",m:"改变",e:"to make different",l:"common",lt:"C"},
{w:"chase",m:"追赶",e:"to run after",l:"common",lt:"C"},
{w:"chest",m:"胸部",e:"front of body",l:"common",lt:"C"},
{w:"child",m:"孩子",e:"young person",l:"common",lt:"C"},
{w:"city",m:"城市",e:"big town",l:"common",lt:"C"},
{w:"class",m:"班级",e:"group of students",l:"common",lt:"C"},
{w:"claw",m:"爪子",e:"sharp nail on animal",l:"common",lt:"C"},
{w:"clean",m:"干净的",e:"not dirty",l:"common",lt:"C"},
{w:"climb",m:"攀爬",e:"to go up",l:"common",lt:"C"},
{w:"clock",m:"时钟",e:"tells the time",l:"common",lt:"C"},
{w:"close",m:"关闭",e:"to shut",l:"common",lt:"C"},
{w:"colour",m:"颜色",e:"red, blue, green etc.",l:"common",lt:"C"},
{w:"contain",m:"包含",e:"to hold inside",l:"common",lt:"C"},
{w:"cough",m:"咳嗽",e:"push air from throat",l:"common",lt:"C"},
{w:"could",m:"能够",e:"was able to",l:"common",lt:"C"},
{w:"couple",m:"一对",e:"two together",l:"common",lt:"C"},
{w:"cracked",m:"裂开的",e:"broken a little",l:"common",lt:"C"},
{w:"crime",m:"犯罪",e:"breaking the law",l:"common",lt:"C"},
{w:"crowd",m:"人群",e:"lots of people",l:"common",lt:"C"},
{w:"calm",m:"平静的",e:"quiet, peaceful",l:"difficult",lt:"C"},
{w:"carriage",m:"马车",e:"wheeled vehicle",l:"difficult",lt:"C"},
{w:"category",m:"类别",e:"group, type",l:"difficult",lt:"C"},
{w:"celebration",m:"庆祝",e:"a party for something",l:"difficult",lt:"C"},
{w:"certain",m:"确定的",e:"sure, definite",l:"difficult",lt:"C"},
{w:"character",m:"角色",e:"person in a story",l:"difficult",lt:"C"},
{w:"cheques",m:"支票",e:"paper to pay money",l:"difficult",lt:"C"},
{w:"chocolate",m:"巧克力",e:"sweet brown treat",l:"difficult",lt:"C"},
{w:"circuit",m:"电路",e:"path for electricity",l:"difficult",lt:"C"},
{w:"college",m:"大学",e:"school after high school",l:"difficult",lt:"C"},
{w:"community",m:"社区",e:"people living together",l:"difficult",lt:"C"},
{w:"competition",m:"比赛",e:"contest to win",l:"difficult",lt:"C"},
{w:"complaining",m:"抱怨",e:"saying you're unhappy",l:"difficult",lt:"C"},
{w:"complete",m:"完成",e:"to finish",l:"difficult",lt:"C"},
{w:"concerned",m:"担心的",e:"worried about",l:"difficult",lt:"C"},
{w:"confidence",m:"自信",e:"believing in yourself",l:"difficult",lt:"C"},
{w:"consider",m:"考虑",e:"to think about",l:"difficult",lt:"C"},
{w:"considerate",m:"体贴的",e:"thinking of others",l:"difficult",lt:"C"},
{w:"continued",m:"继续了",e:"kept going",l:"difficult",lt:"C"},
{w:"contraptions",m:"装置",e:"strange machines",l:"difficult",lt:"C"},
{w:"convince",m:"说服",e:"make someone agree",l:"difficult",lt:"C"},
{w:"coordinator",m:"协调员",e:"person who organises",l:"difficult",lt:"C"},
{w:"corpses",m:"尸体",e:"dead bodies",l:"difficult",lt:"C"},
{w:"creature",m:"生物",e:"living thing",l:"difficult",lt:"C"},
{w:"crevice",m:"裂缝",e:"narrow crack",l:"difficult",lt:"C"},
{w:"criminal",m:"罪犯",e:"person who breaks law",l:"difficult",lt:"C"},
{w:"crystal",m:"水晶",e:"clear shiny stone",l:"difficult",lt:"C"},
{w:"curious",m:"好奇的",e:"wanting to know",l:"difficult",lt:"C"},
{w:"camouflage",m:"伪装",e:"hide by blending in",l:"challenging",lt:"C"},
{w:"carcasses",m:"尸体",e:"dead animal bodies",l:"challenging",lt:"C"},
{w:"changeable",m:"多变的",e:"likely to change",l:"challenging",lt:"C"},
{w:"climatic",m:"气候的",e:"about the weather",l:"challenging",lt:"C"},
{w:"colloquial",m:"口语的",e:"everyday speech",l:"challenging",lt:"C"},
{w:"colossal",m:"巨大的",e:"extremely big",l:"challenging",lt:"C"},
{w:"column",m:"柱子",e:"tall post or list",l:"challenging",lt:"C"},
{w:"competence",m:"能力",e:"being able to do well",l:"challenging",lt:"C"},
{w:"complementary",m:"互补的",e:"completing each other",l:"challenging",lt:"C"},
{w:"complimentary",m:"赞美的",e:"saying nice things, free",l:"challenging",lt:"C"},
{w:"conscience",m:"良心",e:"knowing right from wrong",l:"challenging",lt:"C"},
{w:"conscious",m:"有意识的",e:"awake, aware",l:"challenging",lt:"C"},
{w:"consequently",m:"因此",e:"as a result",l:"challenging",lt:"C"},
{w:"correspond",m:"通信",e:"to write to each other",l:"challenging",lt:"C"},
{w:"courageous",m:"勇敢的",e:"very brave",l:"challenging",lt:"C"},
{w:"cylinder",m:"圆柱体",e:"tube shape",l:"challenging",lt:"C"},
{w:"day",m:"天",e:"24 hours",l:"simple",lt:"D"},
{w:"deep",m:"深的",e:"far down",l:"simple",lt:"D"},
{w:"did",m:"做了",e:"past tense of do",l:"simple",lt:"D"},
{w:"dog",m:"狗",e:"pet that barks",l:"simple",lt:"D"},
{w:"doll",m:"娃娃",e:"toy person",l:"simple",lt:"D"},
{w:"dot",m:"点",e:"small round mark",l:"simple",lt:"D"},
{w:"drag",m:"拖",e:"to pull along",l:"simple",lt:"D"},
{w:"dress",m:"裙子",e:"clothing girls wear",l:"simple",lt:"D"},
{w:"drip",m:"滴",e:"water falling slowly",l:"simple",lt:"D"},
{w:"drop",m:"掉落",e:"to let fall",l:"simple",lt:"D"},
{w:"drum",m:"鼓",e:"hit to make music",l:"simple",lt:"D"},
{w:"dark",m:"黑暗的",e:"no light",l:"common",lt:"D"},
{w:"dead",m:"死的",e:"not alive",l:"common",lt:"D"},
{w:"destroy",m:"摧毁",e:"to break completely",l:"common",lt:"D"},
{w:"detail",m:"细节",e:"small part",l:"common",lt:"D"},
{w:"didn't",m:"没有",e:"did not",l:"common",lt:"D"},
{w:"different",m:"不同的",e:"not the same",l:"common",lt:"D"},
{w:"disarm",m:"解除武装",e:"take weapons away",l:"common",lt:"D"},
{w:"discuss",m:"讨论",e:"to talk about",l:"common",lt:"D"},
{w:"distance",m:"距离",e:"how far away",l:"common",lt:"D"},
{w:"does",m:"做",e:"form of 'do'",l:"common",lt:"D"},
{w:"doesn't",m:"不",e:"does not",l:"common",lt:"D"},
{w:"don't",m:"不要",e:"do not",l:"common",lt:"D"},
{w:"door",m:"门",e:"opens to go through",l:"common",lt:"D"},
{w:"downstairs",m:"楼下",e:"lower floor",l:"common",lt:"D"},
{w:"dragon",m:"龙",e:"fire-breathing creature",l:"common",lt:"D"},
{w:"draw",m:"画",e:"to make a picture",l:"common",lt:"D"},
{w:"dream",m:"梦",e:"pictures while sleeping",l:"common",lt:"D"},
{w:"dry",m:"干的",e:"not wet",l:"common",lt:"D"},
{w:"during",m:"期间",e:"while something happens",l:"common",lt:"D"},
{w:"damage",m:"损坏",e:"to break or harm",l:"difficult",lt:"D"},
{w:"dangerous",m:"危险的",e:"not safe",l:"difficult",lt:"D"},
{w:"decided",m:"决定了",e:"made a choice",l:"difficult",lt:"D"},
{w:"decision",m:"决定",e:"a choice",l:"difficult",lt:"D"},
{w:"decorate",m:"装饰",e:"to make pretty",l:"difficult",lt:"D"},
{w:"defence",m:"防御",e:"protection",l:"difficult",lt:"D"},
{w:"delicious",m:"美味的",e:"tastes very good",l:"difficult",lt:"D"},
{w:"demolished",m:"拆毁了",e:"knocked down",l:"difficult",lt:"D"},
{w:"demonstrate",m:"演示",e:"to show how",l:"difficult",lt:"D"},
{w:"depot",m:"仓库",e:"storage place",l:"difficult",lt:"D"},
{w:"depression",m:"抑郁",e:"deep sadness",l:"difficult",lt:"D"},
{w:"deprived",m:"被剥夺的",e:"taken away from",l:"difficult",lt:"D"},
{w:"deserts",m:"沙漠",e:"dry sandy land",l:"difficult",lt:"D"},
{w:"dessert",m:"甜点",e:"sweet food after meal",l:"difficult",lt:"D"},
{w:"designed",m:"设计了",e:"planned and made",l:"difficult",lt:"D"},
{w:"detective",m:"侦探",e:"person who solves crime",l:"difficult",lt:"D"},
{w:"digest",m:"消化",e:"break down food",l:"difficult",lt:"D"},
{w:"disappear",m:"消失",e:"to go away, vanish",l:"difficult",lt:"D"},
{w:"disappointed",m:"失望的",e:"sad about result",l:"difficult",lt:"D"},
{w:"discover",m:"发现",e:"to find something new",l:"difficult",lt:"D"},
{w:"drawer",m:"抽屉",e:"sliding box in desk",l:"difficult",lt:"D"},
{w:"drought",m:"干旱",e:"no rain for long time",l:"difficult",lt:"D"},
{w:"dye",m:"染料",e:"colour for hair/cloth",l:"difficult",lt:"D"},
{w:"debris",m:"碎片",e:"broken pieces",l:"challenging",lt:"D"},
{w:"decomposed",m:"腐烂的",e:"rotted away",l:"challenging",lt:"D"},
{w:"deficient",m:"不足的",e:"not enough",l:"challenging",lt:"D"},
{w:"definitely",m:"肯定地",e:"for sure",l:"challenging",lt:"D"},
{w:"dependency",m:"依赖",e:"needing something",l:"challenging",lt:"D"},
{w:"desiccate",m:"干燥",e:"to dry out completely",l:"challenging",lt:"D"},
{w:"desperate",m:"绝望的",e:"needing help badly",l:"challenging",lt:"D"},
{w:"desperation",m:"绝望",e:"feeling hopeless",l:"challenging",lt:"D"},
{w:"dominant",m:"占主导的",e:"most powerful",l:"challenging",lt:"D"},
{w:"draught",m:"气流",e:"cold air blowing in",l:"challenging",lt:"D"},
{w:"dungeon",m:"地牢",e:"underground prison",l:"challenging",lt:"D"},
{w:"eat",m:"吃",e:"to put food in mouth",l:"simple",lt:"E"},
{w:"egg",m:"蛋",e:"comes from a chicken",l:"simple",lt:"E"},
{w:"end",m:"结束",e:"the last part",l:"simple",lt:"E"},
{w:"even",m:"甚至",e:"also, flat",l:"simple",lt:"E"},
{w:"ever",m:"曾经",e:"at any time",l:"simple",lt:"E"},
{w:"earth",m:"地球",e:"our planet",l:"common",lt:"E"},
{w:"enemy",m:"敌人",e:"someone against you",l:"common",lt:"E"},
{w:"enjoy",m:"享受",e:"to like doing",l:"common",lt:"E"},
{w:"enough",m:"足够",e:"as much as needed",l:"common",lt:"E"},
{w:"every",m:"每个",e:"all, each one",l:"common",lt:"E"},
{w:"everybody",m:"每个人",e:"all people",l:"common",lt:"E"},
{w:"everyone",m:"每个人",e:"all people",l:"common",lt:"E"},
{w:"everywhere",m:"到处",e:"in all places",l:"common",lt:"E"},
{w:"evil",m:"邪恶的",e:"very bad, wicked",l:"common",lt:"E"},
{w:"example",m:"例子",e:"one to show others",l:"common",lt:"E"},
{w:"explain",m:"解释",e:"to tell how or why",l:"common",lt:"E"},
{w:"eyes",m:"眼睛",e:"you see with them",l:"common",lt:"E"},
{w:"easiest",m:"最简单的",e:"most easy",l:"difficult",lt:"E"},
{w:"echoed",m:"回响了",e:"sound bounced back",l:"difficult",lt:"E"},
{w:"edible",m:"可食用的",e:"safe to eat",l:"difficult",lt:"E"},
{w:"educational",m:"教育的",e:"helps you learn",l:"difficult",lt:"E"},
{w:"eerie",m:"诡异的",e:"strange and scary",l:"difficult",lt:"E"},
{w:"effect",m:"效果",e:"result of something",l:"difficult",lt:"E"},
{w:"effective",m:"有效的",e:"works well",l:"difficult",lt:"E"},
{w:"emerged",m:"出现了",e:"came out",l:"difficult",lt:"E"},
{w:"endangered",m:"濒危的",e:"might die out",l:"difficult",lt:"E"},
{w:"energy",m:"能量",e:"power to do things",l:"difficult",lt:"E"},
{w:"engage",m:"参与",e:"to join in",l:"difficult",lt:"E"},
{w:"engine",m:"引擎",e:"machine that powers",l:"difficult",lt:"E"},
{w:"enjoyable",m:"愉快的",e:"fun, pleasant",l:"difficult",lt:"E"},
{w:"enormous",m:"巨大的",e:"very very big",l:"difficult",lt:"E"},
{w:"ensure",m:"确保",e:"to make sure",l:"difficult",lt:"E"},
{w:"episode",m:"一集",e:"one part of a show",l:"difficult",lt:"E"},
{w:"especially",m:"尤其",e:"more than others",l:"difficult",lt:"E"},
{w:"esteem",m:"尊重",e:"respect",l:"difficult",lt:"E"},
{w:"except",m:"除了",e:"but not",l:"difficult",lt:"E"},
{w:"exciting",m:"令人兴奋的",e:"makes you happy",l:"difficult",lt:"E"},
{w:"exclaimed",m:"惊叫",e:"said with surprise",l:"difficult",lt:"E"},
{w:"exert",m:"施加",e:"to use force",l:"difficult",lt:"E"},
{w:"expensive",m:"昂贵的",e:"costs a lot",l:"difficult",lt:"E"},
{w:"experience",m:"经历",e:"something that happened",l:"difficult",lt:"E"},
{w:"explosion",m:"爆炸",e:"big bang",l:"difficult",lt:"E"},
{w:"extremely",m:"极其",e:"very very much",l:"difficult",lt:"E"},
{w:"effervescent",m:"冒泡的",e:"bubbly, fizzy",l:"challenging",lt:"E"},
{w:"efficient",m:"高效的",e:"works well, no waste",l:"challenging",lt:"E"},
{w:"embarrassed",m:"尴尬的",e:"feeling shy or silly",l:"challenging",lt:"E"},
{w:"environment",m:"环境",e:"world around us",l:"challenging",lt:"E"},
{w:"euphoric",m:"欣快的",e:"extremely happy",l:"challenging",lt:"E"},
{w:"exaggerate",m:"夸张",e:"make bigger than true",l:"challenging",lt:"E"},
{w:"exhilarating",m:"令人振奋",e:"very exciting",l:"challenging",lt:"E"},
{w:"explanatory",m:"解释性的",e:"helps explain",l:"challenging",lt:"E"},
{w:"fat",m:"胖的",e:"not thin",l:"simple",lt:"F"},
{w:"feel",m:"感觉",e:"to touch or sense",l:"simple",lt:"F"},
{w:"feet",m:"脚",e:"at end of legs",l:"simple",lt:"F"},
{w:"fell",m:"摔倒了",e:"dropped down",l:"simple",lt:"F"},
{w:"fill",m:"填满",e:"to make full",l:"simple",lt:"F"},
{w:"fit",m:"合适",e:"right size",l:"simple",lt:"F"},
{w:"five",m:"五",e:"number 5",l:"simple",lt:"F"},
{w:"food",m:"食物",e:"what we eat",l:"simple",lt:"F"},
{w:"for",m:"为了",e:"meant for",l:"simple",lt:"F"},
{w:"four",m:"四",e:"number 4",l:"simple",lt:"F"},
{w:"from",m:"从",e:"coming out of",l:"simple",lt:"F"},
{w:"fun",m:"乐趣",e:"good time",l:"simple",lt:"F"},
{w:"face",m:"脸",e:"front of head",l:"common",lt:"F"},
{w:"fair",m:"公平的",e:"equal for all",l:"common",lt:"F"},
{w:"family",m:"家庭",e:"parents and children",l:"common",lt:"F"},
{w:"fear",m:"害怕",e:"feeling scared",l:"common",lt:"F"},
{w:"feather",m:"羽毛",e:"bird's covering",l:"common",lt:"F"},
{w:"feelings",m:"感受",e:"emotions inside",l:"common",lt:"F"},
{w:"fighting",m:"打架",e:"hitting each other",l:"common",lt:"F"},
{w:"finally",m:"终于",e:"at last",l:"common",lt:"F"},
{w:"fine",m:"好的",e:"okay, good",l:"common",lt:"F"},
{w:"first",m:"第一",e:"before all others",l:"common",lt:"F"},
{w:"flapping",m:"拍打",e:"moving wings up/down",l:"common",lt:"F"},
{w:"flies",m:"飞",e:"moves through air",l:"common",lt:"F"},
{w:"flight",m:"飞行",e:"trip in the air",l:"common",lt:"F"},
{w:"floor",m:"地板",e:"bottom of room",l:"common",lt:"F"},
{w:"flower",m:"花",e:"pretty plant part",l:"common",lt:"F"},
{w:"fly",m:"飞",e:"move through air",l:"common",lt:"F"},
{w:"followed",m:"跟随了",e:"went after",l:"common",lt:"F"},
{w:"footsteps",m:"脚步",e:"sounds of walking",l:"common",lt:"F"},
{w:"forest",m:"森林",e:"lots of trees",l:"common",lt:"F"},
{w:"found",m:"找到了",e:"discovered",l:"common",lt:"F"},
{w:"friend",m:"朋友",e:"person you like",l:"common",lt:"F"},
{w:"fright",m:"惊吓",e:"sudden fear",l:"common",lt:"F"},
{w:"fruit",m:"水果",e:"apple, banana etc.",l:"common",lt:"F"},
{w:"funny",m:"有趣的",e:"makes you laugh",l:"common",lt:"F"},
{w:"famous",m:"出名的",e:"known by many people",l:"difficult",lt:"F"},
{w:"favourite",m:"最喜欢的",e:"liked the most",l:"difficult",lt:"F"},
{w:"features",m:"特征",e:"parts that stand out",l:"difficult",lt:"F"},
{w:"february",m:"二月",e:"month after January",l:"difficult",lt:"F"},
{w:"fellowship",m:"友谊",e:"friendship group",l:"difficult",lt:"F"},
{w:"fete",m:"游园会",e:"outdoor fair, party",l:"difficult",lt:"F"},
{w:"fibre",m:"纤维",e:"thin thread",l:"difficult",lt:"F"},
{w:"fiction",m:"小说",e:"made-up story",l:"difficult",lt:"F"},
{w:"field",m:"田地",e:"open grassy area",l:"difficult",lt:"F"},
{w:"fierce",m:"凶猛的",e:"wild and scary",l:"difficult",lt:"F"},
{w:"formal",m:"正式的",e:"proper, official",l:"difficult",lt:"F"},
{w:"formation",m:"形成",e:"shape or arrangement",l:"difficult",lt:"F"},
{w:"fractures",m:"骨折",e:"broken bones",l:"difficult",lt:"F"},
{w:"fragile",m:"脆弱的",e:"easy to break",l:"difficult",lt:"F"},
{w:"frenzied",m:"疯狂的",e:"wild and crazy",l:"difficult",lt:"F"},
{w:"frightened",m:"害怕的",e:"feeling scared",l:"difficult",lt:"F"},
{w:"furniture",m:"家具",e:"tables, chairs etc.",l:"difficult",lt:"F"},
{w:"further",m:"更远",e:"more far away",l:"difficult",lt:"F"},
{w:"facilities",m:"设施",e:"buildings to use",l:"challenging",lt:"F"},
{w:"fascinating",m:"迷人的",e:"very interesting",l:"challenging",lt:"F"},
{w:"fluorescent",m:"荧光的",e:"bright glowing colour",l:"challenging",lt:"F"},
{w:"fuchsia",m:"紫红色",e:"pink-purple colour",l:"challenging",lt:"F"},
{w:"furnace",m:"熔炉",e:"very hot oven",l:"challenging",lt:"F"},
{w:"futile",m:"徒劳的",e:"useless, won't work",l:"challenging",lt:"F"},
{w:"get",m:"得到",e:"to receive",l:"simple",lt:"G"},
{w:"go",m:"去",e:"to move somewhere",l:"simple",lt:"G"},
{w:"going",m:"去",e:"moving to a place",l:"simple",lt:"G"},
{w:"good",m:"好的",e:"not bad",l:"simple",lt:"G"},
{w:"got",m:"得到了",e:"past tense of get",l:"simple",lt:"G"},
{w:"grass",m:"草",e:"green ground plant",l:"simple",lt:"G"},
{w:"game",m:"游戏",e:"something to play",l:"common",lt:"G"},
{w:"garden",m:"花园",e:"place to grow plants",l:"common",lt:"G"},
{w:"gardening",m:"园艺",e:"working in garden",l:"common",lt:"G"},
{w:"getting",m:"得到",e:"receiving",l:"common",lt:"G"},
{w:"goes",m:"去",e:"moves somewhere",l:"common",lt:"G"},
{w:"golden",m:"金色的",e:"colour of gold",l:"common",lt:"G"},
{w:"goodness",m:"善良",e:"being good",l:"common",lt:"G"},
{w:"globe",m:"地球仪",e:"round model of earth",l:"common",lt:"G"},
{w:"great",m:"很棒的",e:"very good",l:"common",lt:"G"},
{w:"green",m:"绿色",e:"colour of grass",l:"common",lt:"G"},
{w:"ground",m:"地面",e:"earth under feet",l:"common",lt:"G"},
{w:"group",m:"组",e:"people together",l:"common",lt:"G"},
{w:"galaxy",m:"银河",e:"group of stars",l:"difficult",lt:"G"},
{w:"generation",m:"一代人",e:"people born same time",l:"difficult",lt:"G"},
{w:"gesture",m:"手势",e:"movement of hands",l:"difficult",lt:"G"},
{w:"gigantic",m:"巨大的",e:"really really big",l:"difficult",lt:"G"},
{w:"glacier",m:"冰川",e:"huge ice river",l:"difficult",lt:"G"},
{w:"global",m:"全球的",e:"about the whole world",l:"difficult",lt:"G"},
{w:"gnawed",m:"啃了",e:"chewed on",l:"difficult",lt:"G"},
{w:"goblet",m:"高脚杯",e:"fancy drinking cup",l:"difficult",lt:"G"},
{w:"government",m:"政府",e:"people who run country",l:"difficult",lt:"G"},
{w:"graphics",m:"图形",e:"pictures on screen",l:"difficult",lt:"G"},
{w:"grumble",m:"抱怨",e:"to complain quietly",l:"difficult",lt:"G"},
{w:"guess",m:"猜",e:"to try to answer",l:"difficult",lt:"G"},
{w:"gauge",m:"测量",e:"to measure",l:"challenging",lt:"G"},
{w:"ghoul",m:"食尸鬼",e:"scary ghost creature",l:"challenging",lt:"G"},
{w:"grandeur",m:"壮丽",e:"great beauty, big",l:"challenging",lt:"G"},
{w:"guaranteed",m:"保证的",e:"promised for sure",l:"challenging",lt:"G"},
{w:"guillotine",m:"断头台",e:"cutting machine",l:"challenging",lt:"G"},
{w:"gynaecology",m:"妇科",e:"women's health study",l:"challenging",lt:"G"},
{w:"hand",m:"手",e:"at end of arm",l:"simple",lt:"H"},
{w:"hard",m:"硬的",e:"not soft, difficult",l:"simple",lt:"H"},
{w:"has",m:"有",e:"owns, possesses",l:"simple",lt:"H"},
{w:"hat",m:"帽子",e:"wear on head",l:"simple",lt:"H"},
{w:"have",m:"有",e:"to own",l:"simple",lt:"H"},
{w:"he",m:"他",e:"a boy or man",l:"simple",lt:"H"},
{w:"help",m:"帮助",e:"to assist",l:"simple",lt:"H"},
{w:"her",m:"她的",e:"belonging to a girl",l:"simple",lt:"H"},
{w:"him",m:"他",e:"a boy (object)",l:"simple",lt:"H"},
{w:"hot",m:"热的",e:"very warm",l:"simple",lt:"H"},
{w:"how",m:"怎样",e:"in what way",l:"simple",lt:"H"},
{w:"habit",m:"习惯",e:"thing you always do",l:"common",lt:"H"},
{w:"hair",m:"头发",e:"grows on head",l:"common",lt:"H"},
{w:"happen",m:"发生",e:"to take place",l:"common",lt:"H"},
{w:"happiest",m:"最快乐的",e:"most happy",l:"common",lt:"H"},
{w:"happy",m:"快乐的",e:"feeling good",l:"common",lt:"H"},
{w:"hardly",m:"几乎不",e:"almost not",l:"common",lt:"H"},
{w:"hatch",m:"孵化",e:"come out of egg",l:"common",lt:"H"},
{w:"heaps",m:"很多",e:"lots and lots",l:"common",lt:"H"},
{w:"hear",m:"听",e:"use ears (not 'here')",l:"common",lt:"H"},
{w:"here",m:"这里",e:"in this place (not 'hear')",l:"common",lt:"H"},
{w:"heard",m:"听到了",e:"past tense of hear",l:"common",lt:"H"},
{w:"hearing",m:"听觉",e:"using your ears",l:"common",lt:"H"},
{w:"heavier",m:"更重的",e:"weighs more",l:"common",lt:"H"},
{w:"holidays",m:"假期",e:"time off school",l:"common",lt:"H"},
{w:"home",m:"家",e:"where you live",l:"common",lt:"H"},
{w:"hope",m:"希望",e:"to wish for",l:"common",lt:"H"},
{w:"hoping",m:"希望着",e:"wishing for",l:"common",lt:"H"},
{w:"hospital",m:"医院",e:"where sick people go",l:"common",lt:"H"},
{w:"house",m:"房子",e:"building to live in",l:"common",lt:"H"},
{w:"however",m:"然而",e:"but, on other hand",l:"common",lt:"H"},
{w:"huge",m:"巨大的",e:"very big",l:"common",lt:"H"},
{w:"humans",m:"人类",e:"people",l:"common",lt:"H"},
{w:"hundred",m:"一百",e:"number 100",l:"common",lt:"H"},
{w:"hunted",m:"猎杀了",e:"chased to catch",l:"common",lt:"H"},
{w:"hammock",m:"吊床",e:"hanging bed",l:"difficult",lt:"H"},
{w:"haphazard",m:"杂乱的",e:"messy, no plan",l:"difficult",lt:"H"},
{w:"haste",m:"匆忙",e:"being in a rush",l:"difficult",lt:"H"},
{w:"haul",m:"拖",e:"to pull hard",l:"difficult",lt:"H"},
{w:"healthy",m:"健康的",e:"not sick",l:"difficult",lt:"H"},
{w:"heir",m:"继承人",e:"person who gets next",l:"difficult",lt:"H"},
{w:"herd",m:"兽群",e:"group of animals",l:"difficult",lt:"H"},
{w:"hesitated",m:"犹豫了",e:"paused, unsure",l:"difficult",lt:"H"},
{w:"hilarious",m:"搞笑的",e:"very very funny",l:"difficult",lt:"H"},
{w:"history",m:"历史",e:"what happened before",l:"difficult",lt:"H"},
{w:"hoarse",m:"沙哑的",e:"rough voice",l:"difficult",lt:"H"},
{w:"honest",m:"诚实的",e:"tells the truth",l:"difficult",lt:"H"},
{w:"hopefully",m:"希望地",e:"with hope",l:"difficult",lt:"H"},
{w:"horrified",m:"惊恐的",e:"very very scared",l:"difficult",lt:"H"},
{w:"hostel",m:"旅社",e:"cheap place to stay",l:"difficult",lt:"H"},
{w:"humorous",m:"幽默的",e:"funny",l:"difficult",lt:"H"},
{w:"hurriedly",m:"匆忙地",e:"in a rush",l:"difficult",lt:"H"},
{w:"hygiene",m:"卫生",e:"keeping clean",l:"difficult",lt:"H"},
{w:"haemoglobin",m:"血红蛋白",e:"red part of blood",l:"challenging",lt:"H"},
{w:"hallucinate",m:"幻觉",e:"see things not there",l:"challenging",lt:"H"},
{w:"helium",m:"氦气",e:"gas that floats balloons",l:"challenging",lt:"H"},
{w:"hesitance",m:"犹豫",e:"not being sure",l:"challenging",lt:"H"},
{w:"humanitarian",m:"人道主义",e:"helping people",l:"challenging",lt:"H"},
{w:"i",m:"我",e:"myself",l:"simple",lt:"I"},
{w:"if",m:"如果",e:"in case that",l:"simple",lt:"I"},
{w:"in",m:"在里面",e:"inside",l:"simple",lt:"I"},
{w:"into",m:"进入",e:"going inside",l:"simple",lt:"I"},
{w:"is",m:"是",e:"form of 'to be'",l:"simple",lt:"I"},
{w:"it",m:"它",e:"that thing",l:"simple",lt:"I"},
{w:"ice",m:"冰",e:"frozen water",l:"common",lt:"I"},
{w:"idea",m:"想法",e:"a thought",l:"common",lt:"I"},
{w:"important",m:"重要的",e:"matters a lot",l:"common",lt:"I"},
{w:"insects",m:"昆虫",e:"small bugs",l:"common",lt:"I"},
{w:"inside",m:"里面",e:"in something",l:"common",lt:"I"},
{w:"invite",m:"邀请",e:"ask to come",l:"common",lt:"I"},
{w:"islands",m:"岛屿",e:"land in water",l:"common",lt:"I"},
{w:"illegal",m:"非法的",e:"against the law",l:"difficult",lt:"I"},
{w:"imagination",m:"想象力",e:"making pictures in mind",l:"difficult",lt:"I"},
{w:"imaginative",m:"有想象力",e:"good at thinking up",l:"difficult",lt:"I"},
{w:"implicate",m:"牵连",e:"to involve in trouble",l:"difficult",lt:"I"},
{w:"impressed",m:"印象深刻",e:"thought it was great",l:"difficult",lt:"I"},
{w:"improvement",m:"改善",e:"getting better",l:"difficult",lt:"I"},
{w:"including",m:"包括",e:"with, counting in",l:"difficult",lt:"I"},
{w:"inexpert",m:"不熟练的",e:"not skilled",l:"difficult",lt:"I"},
{w:"information",m:"信息",e:"facts, knowledge",l:"difficult",lt:"I"},
{w:"informative",m:"有启发的",e:"teaches you things",l:"difficult",lt:"I"},
{w:"injury",m:"受伤",e:"hurt to body",l:"difficult",lt:"I"},
{w:"insane",m:"疯狂的",e:"crazy",l:"difficult",lt:"I"},
{w:"insolent",m:"无礼的",e:"very rude",l:"difficult",lt:"I"},
{w:"instinct",m:"本能",e:"natural feeling",l:"difficult",lt:"I"},
{w:"insurance",m:"保险",e:"pay to protect",l:"difficult",lt:"I"},
{w:"intelligent",m:"聪明的",e:"very smart",l:"difficult",lt:"I"},
{w:"intention",m:"意图",e:"what you plan to do",l:"difficult",lt:"I"},
{w:"interesting",m:"有趣的",e:"makes you curious",l:"difficult",lt:"I"},
{w:"interrupt",m:"打断",e:"to stop someone talking",l:"difficult",lt:"I"},
{w:"invisible",m:"看不见的",e:"can't be seen",l:"difficult",lt:"I"},
{w:"irrational",m:"不理性的",e:"not making sense",l:"difficult",lt:"I"},
{w:"issue",m:"问题",e:"a problem",l:"difficult",lt:"I"},
{w:"imaginable",m:"可想象的",e:"you can think of",l:"challenging",lt:"I"},
{w:"incandescent",m:"白炽的",e:"glowing with heat",l:"challenging",lt:"I"},
{w:"incompetent",m:"无能的",e:"not able to do well",l:"challenging",lt:"I"},
{w:"inconsequential",m:"无关紧要",e:"not important",l:"challenging",lt:"I"},
{w:"inconsolable",m:"无法安慰",e:"very very sad",l:"challenging",lt:"I"},
{w:"incorporate",m:"合并",e:"to include, add in",l:"challenging",lt:"I"},
{w:"indecipherable",m:"难辨认",e:"can't be read",l:"challenging",lt:"I"},
{w:"insanity",m:"疯狂",e:"being crazy",l:"challenging",lt:"I"},
{w:"interrogate",m:"审问",e:"to question hard",l:"challenging",lt:"I"},
{w:"intrigue",m:"阴谋",e:"secret plan, interest",l:"challenging",lt:"I"},
{w:"intriguing",m:"有趣的",e:"very interesting",l:"challenging",lt:"I"},
{w:"iridescent",m:"彩虹色",e:"shiny rainbow colours",l:"challenging",lt:"I"},
{w:"irrelevant",m:"不相关的",e:"doesn't matter",l:"challenging",lt:"I"},
{w:"irresponsible",m:"不负责的",e:"not careful or wise",l:"challenging",lt:"I"},
{w:"just",m:"刚刚",e:"only, right now",l:"simple",lt:"J"},
{w:"jacket",m:"夹克",e:"short coat",l:"common",lt:"J"},
{w:"joke",m:"笑话",e:"something funny",l:"common",lt:"J"},
{w:"juice",m:"果汁",e:"drink from fruit",l:"common",lt:"J"},
{w:"jump",m:"跳",e:"go up in the air",l:"common",lt:"J"},
{w:"jeopardy",m:"危险",e:"in danger",l:"difficult",lt:"J"},
{w:"jettison",m:"抛弃",e:"throw away",l:"difficult",lt:"J"},
{w:"journey",m:"旅程",e:"a long trip",l:"difficult",lt:"J"},
{w:"jewels",m:"宝石",e:"precious stones",l:"difficult",lt:"J"},
{w:"jewellery",m:"珠宝",e:"rings and necklaces",l:"difficult",lt:"J"},
{w:"judicial",m:"司法的",e:"about courts and law",l:"challenging",lt:"J"},
{w:"keep",m:"保持",e:"to hold on to",l:"simple",lt:"K"},
{w:"kid",m:"小孩",e:"a child",l:"simple",lt:"K"},
{w:"key",m:"钥匙",e:"opens a lock",l:"common",lt:"K"},
{w:"kitten",m:"小猫",e:"baby cat",l:"common",lt:"K"},
{w:"knee",m:"膝盖",e:"middle of leg",l:"common",lt:"K"},
{w:"knows",m:"知道",e:"has knowledge",l:"common",lt:"K"},
{w:"kidnapped",m:"绑架了",e:"taken by force",l:"difficult",lt:"K"},
{w:"kilometres",m:"公里",e:"distance measure",l:"difficult",lt:"K"},
{w:"kiosk",m:"售货亭",e:"small shop stand",l:"difficult",lt:"K"},
{w:"knowledge",m:"知识",e:"what you know",l:"difficult",lt:"K"},
{w:"kaleidoscope",m:"万花筒",e:"tube with patterns",l:"challenging",lt:"K"},
{w:"kayaking",m:"划皮艇",e:"paddling a small boat",l:"challenging",lt:"K"},
{w:"land",m:"陆地",e:"ground, earth",l:"simple",lt:"L"},
{w:"lay",m:"放",e:"to put down",l:"simple",lt:"L"},
{w:"left",m:"左边",e:"not right",l:"simple",lt:"L"},
{w:"leg",m:"腿",e:"walk with it",l:"simple",lt:"L"},
{w:"lets",m:"让",e:"allows",l:"simple",lt:"L"},
{w:"lick",m:"舔",e:"tongue touches",l:"simple",lt:"L"},
{w:"like",m:"喜欢",e:"to enjoy",l:"simple",lt:"L"},
{w:"long",m:"长的",e:"not short",l:"simple",lt:"L"},
{w:"look",m:"看",e:"to use eyes",l:"simple",lt:"L"},
{w:"lot",m:"很多",e:"many, a lot",l:"simple",lt:"L"},
{w:"ladies",m:"女士们",e:"women",l:"common",lt:"L"},
{w:"lake",m:"湖",e:"big body of water",l:"common",lt:"L"},
{w:"large",m:"大的",e:"big",l:"common",lt:"L"},
{w:"laugh",m:"笑",e:"happy sound",l:"common",lt:"L"},
{w:"laying",m:"放置",e:"putting down",l:"common",lt:"L"},
{w:"leaf",m:"叶子",e:"flat green on tree",l:"common",lt:"L"},
{w:"learn",m:"学习",e:"to get knowledge",l:"common",lt:"L"},
{w:"leaves",m:"叶子",e:"more than one leaf",l:"common",lt:"L"},
{w:"leaving",m:"离开",e:"going away",l:"common",lt:"L"},
{w:"length",m:"长度",e:"how long it is",l:"common",lt:"L"},
{w:"lesson",m:"课",e:"time to learn",l:"common",lt:"L"},
{w:"letter",m:"信",e:"written message",l:"common",lt:"L"},
{w:"lifelike",m:"逼真的",e:"looks real",l:"common",lt:"L"},
{w:"light",m:"光",e:"not dark",l:"common",lt:"L"},
{w:"limb",m:"肢",e:"arm or leg",l:"common",lt:"L"},
{w:"little",m:"小的",e:"not big",l:"common",lt:"L"},
{w:"live",m:"住",e:"to be alive, stay",l:"common",lt:"L"},
{w:"living",m:"活着的",e:"being alive",l:"common",lt:"L"},
{w:"local",m:"当地的",e:"nearby",l:"common",lt:"L"},
{w:"loose",m:"松的",e:"not tight",l:"common",lt:"L"},
{w:"lose",m:"丢失",e:"to not have anymore",l:"common",lt:"L"},
{w:"loud",m:"大声的",e:"not quiet",l:"common",lt:"L"},
{w:"love",m:"爱",e:"care for deeply",l:"common",lt:"L"},
{w:"language",m:"语言",e:"words people speak",l:"difficult",lt:"L"},
{w:"lasers",m:"激光",e:"strong light beams",l:"difficult",lt:"L"},
{w:"league",m:"联盟",e:"group of teams",l:"difficult",lt:"L"},
{w:"library",m:"图书馆",e:"place with books",l:"difficult",lt:"L"},
{w:"lightning",m:"闪电",e:"light in a storm",l:"difficult",lt:"L"},
{w:"litany",m:"连祷",e:"long boring list",l:"difficult",lt:"L"},
{w:"literacy",m:"读写能力",e:"reading and writing",l:"difficult",lt:"L"},
{w:"lullaby",m:"摇篮曲",e:"sleep song for baby",l:"difficult",lt:"L"},
{w:"lunar",m:"月球的",e:"about the moon",l:"difficult",lt:"L"},
{w:"lyrebird",m:"琴鸟",e:"bird that copies sounds",l:"difficult",lt:"L"},
{w:"lacerate",m:"撕裂",e:"to cut or tear",l:"challenging",lt:"L"},
{w:"leisure",m:"休闲",e:"free time",l:"challenging",lt:"L"},
{w:"lieutenant",m:"中尉",e:"army officer",l:"challenging",lt:"L"},
{w:"liquefy",m:"液化",e:"turn into liquid",l:"challenging",lt:"L"},
{w:"litigious",m:"好打官司",e:"likes to sue",l:"challenging",lt:"L"},
{w:"longevity",m:"长寿",e:"living a long time",l:"challenging",lt:"L"},
{w:"luminescent",m:"发光的",e:"giving off light",l:"challenging",lt:"L"},
{w:"may",m:"可以",e:"is allowed to",l:"simple",lt:"M"},
{w:"me",m:"我",e:"myself (object)",l:"simple",lt:"M"},
{w:"meet",m:"遇见",e:"to come together",l:"simple",lt:"M"},
{w:"men",m:"男人们",e:"more than one man",l:"simple",lt:"M"},
{w:"milk",m:"牛奶",e:"white drink from cow",l:"simple",lt:"M"},
{w:"much",m:"很多",e:"a lot",l:"simple",lt:"M"},
{w:"my",m:"我的",e:"belongs to me",l:"simple",lt:"M"},
{w:"magazine",m:"杂志",e:"thin book with pictures",l:"common",lt:"M"},
{w:"mainly",m:"主要地",e:"mostly",l:"common",lt:"M"},
{w:"many",m:"很多",e:"a large number",l:"common",lt:"M"},
{w:"mascot",m:"吉祥物",e:"lucky character",l:"common",lt:"M"},
{w:"match",m:"比赛",e:"game, contest",l:"common",lt:"M"},
{w:"meat",m:"肉",e:"food from animals",l:"common",lt:"M"},
{w:"medals",m:"奖牌",e:"prizes for winning",l:"common",lt:"M"},
{w:"medium",m:"中等的",e:"in the middle size",l:"common",lt:"M"},
{w:"menu",m:"菜单",e:"list of food choices",l:"common",lt:"M"},
{w:"merit",m:"优点",e:"good quality",l:"common",lt:"M"},
{w:"messy",m:"脏乱的",e:"not tidy",l:"common",lt:"M"},
{w:"metals",m:"金属",e:"iron, gold etc.",l:"common",lt:"M"},
{w:"might",m:"可能",e:"maybe will",l:"common",lt:"M"},
{w:"migrate",m:"迁徙",e:"move to new place",l:"common",lt:"M"},
{w:"modern",m:"现代的",e:"new, up to date",l:"common",lt:"M"},
{w:"monday",m:"星期一",e:"first day of week",l:"common",lt:"M"},
{w:"moonlight",m:"月光",e:"light from moon",l:"common",lt:"M"},
{w:"moral",m:"道德",e:"about right and wrong",l:"common",lt:"M"},
{w:"more",m:"更多",e:"extra",l:"common",lt:"M"},
{w:"mother",m:"妈妈",e:"female parent",l:"common",lt:"M"},
{w:"move",m:"移动",e:"to go somewhere",l:"common",lt:"M"},
{w:"movie",m:"电影",e:"film to watch",l:"common",lt:"M"},
{w:"muffled",m:"低沉的",e:"quiet, hard to hear",l:"common",lt:"M"},
{w:"music",m:"音乐",e:"songs and sounds",l:"common",lt:"M"},
{w:"magic",m:"魔法",e:"special power",l:"difficult",lt:"M"},
{w:"majestic",m:"雄伟的",e:"grand, like a king",l:"difficult",lt:"M"},
{w:"malt",m:"麦芽",e:"grain used in drinks",l:"difficult",lt:"M"},
{w:"martial",m:"武术的",e:"about fighting",l:"difficult",lt:"M"},
{w:"massive",m:"巨大的",e:"very very big",l:"difficult",lt:"M"},
{w:"matted",m:"缠结的",e:"tangled together",l:"difficult",lt:"M"},
{w:"mayor",m:"市长",e:"leader of a city",l:"difficult",lt:"M"},
{w:"measured",m:"测量了",e:"found the size",l:"difficult",lt:"M"},
{w:"medicine",m:"药",e:"helps when sick",l:"difficult",lt:"M"},
{w:"medieval",m:"中世纪的",e:"from long ago",l:"difficult",lt:"M"},
{w:"minerals",m:"矿物",e:"natural rocks",l:"difficult",lt:"M"},
{w:"molecule",m:"分子",e:"tiny tiny piece",l:"difficult",lt:"M"},
{w:"molten",m:"熔化的",e:"melted by heat",l:"difficult",lt:"M"},
{w:"moult",m:"换毛",e:"lose old feathers",l:"difficult",lt:"M"},
{w:"mountain",m:"山",e:"very tall land",l:"difficult",lt:"M"},
{w:"mucous",m:"黏液的",e:"slimy (adjective)",l:"difficult",lt:"M"},
{w:"mucus",m:"黏液",e:"slimy stuff in nose",l:"difficult",lt:"M"},
{w:"muscle",m:"肌肉",e:"body part for moving",l:"difficult",lt:"M"},
{w:"muscular",m:"肌肉发达",e:"strong body",l:"difficult",lt:"M"},
{w:"museum",m:"博物馆",e:"place with old things",l:"difficult",lt:"M"},
{w:"mysterious",m:"神秘的",e:"hard to explain",l:"difficult",lt:"M"},
{w:"mystery",m:"谜",e:"something unknown",l:"difficult",lt:"M"},
{w:"mystic",m:"神秘的",e:"magical, spiritual",l:"difficult",lt:"M"},
{w:"myth",m:"神话",e:"old made-up story",l:"difficult",lt:"M"},
{w:"magnificent",m:"壮丽的",e:"wonderful, grand",l:"challenging",lt:"M"},
{w:"malaria",m:"疟疾",e:"disease from mosquito",l:"challenging",lt:"M"},
{w:"mandible",m:"下颚",e:"lower jaw bone",l:"challenging",lt:"M"},
{w:"manoeuvre",m:"操控",e:"to move carefully",l:"challenging",lt:"M"},
{w:"mathematician",m:"数学家",e:"maths expert",l:"challenging",lt:"M"},
{w:"mediaeval",m:"中世纪的",e:"from the middle ages",l:"challenging",lt:"M"},
{w:"mesmerised",m:"着迷的",e:"can't look away",l:"challenging",lt:"M"},
{w:"miniature",m:"微型的",e:"very very small",l:"challenging",lt:"M"},
{w:"minions",m:"仆从",e:"helpers, followers",l:"challenging",lt:"M"},
{w:"mischievous",m:"淘气的",e:"naughty, playful",l:"challenging",lt:"M"},
{w:"misconstrue",m:"误解",e:"to understand wrong",l:"challenging",lt:"M"},
{w:"misogyny",m:"厌女",e:"dislike of women",l:"challenging",lt:"M"},
{w:"name",m:"名字",e:"what you are called",l:"simple",lt:"N"},
{w:"new",m:"新的",e:"not old",l:"simple",lt:"N"},
{w:"no",m:"不",e:"opposite of yes",l:"simple",lt:"N"},
{w:"not",m:"不",e:"makes it negative",l:"simple",lt:"N"},
{w:"nut",m:"坚果",e:"hard-shell seed",l:"simple",lt:"N"},
{w:"native",m:"本地的",e:"from that place",l:"common",lt:"N"},
{w:"naughty",m:"淘气的",e:"badly behaved",l:"common",lt:"N"},
{w:"nearest",m:"最近的",e:"closest",l:"common",lt:"N"},
{w:"necklace",m:"项链",e:"jewellery for neck",l:"common",lt:"N"},
{w:"nectar",m:"花蜜",e:"sweet flower juice",l:"common",lt:"N"},
{w:"nephew",m:"侄子",e:"brother's son",l:"common",lt:"N"},
{w:"nice",m:"好的",e:"pleasant, kind",l:"common",lt:"N"},
{w:"night",m:"夜晚",e:"when it's dark",l:"common",lt:"N"},
{w:"noise",m:"噪音",e:"loud sound",l:"common",lt:"N"},
{w:"noisy",m:"吵闹的",e:"making lots of sound",l:"common",lt:"N"},
{w:"numb",m:"麻木的",e:"can't feel anything",l:"common",lt:"N"},
{w:"natural",m:"自然的",e:"from nature",l:"difficult",lt:"N"},
{w:"negligent",m:"疏忽的",e:"not careful enough",l:"difficult",lt:"N"},
{w:"neighbour",m:"邻居",e:"person next door",l:"difficult",lt:"N"},
{w:"neither",m:"都不",e:"not this one or that",l:"difficult",lt:"N"},
{w:"nervous",m:"紧张的",e:"worried, anxious",l:"difficult",lt:"N"},
{w:"niece",m:"侄女",e:"brother's daughter",l:"difficult",lt:"N"},
{w:"normality",m:"正常",e:"being normal",l:"difficult",lt:"N"},
{w:"nutrition",m:"营养",e:"food for health",l:"difficult",lt:"N"},
{w:"notice",m:"注意到",e:"to see, spot",l:"difficult",lt:"N"},
{w:"naivety",m:"天真",e:"being too trusting",l:"challenging",lt:"N"},
{w:"narcissist",m:"自恋者",e:"loves only themselves",l:"challenging",lt:"N"},
{w:"necessary",m:"必要的",e:"must have",l:"challenging",lt:"N"},
{w:"nonchalant",m:"漫不经心",e:"not worried at all",l:"challenging",lt:"N"},
{w:"noticeable",m:"显著的",e:"easy to see",l:"challenging",lt:"N"},
{w:"notoriety",m:"臭名",e:"being famous for bad",l:"challenging",lt:"N"},
{w:"nuisance",m:"讨厌鬼",e:"annoying thing",l:"challenging",lt:"N"},
{w:"of",m:"的",e:"belonging to",l:"simple",lt:"O"},
{w:"old",m:"旧的",e:"not new",l:"simple",lt:"O"},
{w:"one",m:"一",e:"number 1",l:"simple",lt:"O"},
{w:"our",m:"我们的",e:"belongs to us",l:"simple",lt:"O"},
{w:"out",m:"外面",e:"not inside",l:"simple",lt:"O"},
{w:"obtain",m:"获得",e:"to get",l:"common",lt:"O"},
{w:"ocean",m:"海洋",e:"big body of water",l:"common",lt:"O"},
{w:"octopus",m:"章鱼",e:"8-arm sea animal",l:"common",lt:"O"},
{w:"off",m:"关",e:"not on",l:"common",lt:"O"},
{w:"older",m:"更老的",e:"more old",l:"common",lt:"O"},
{w:"once",m:"一次",e:"one time",l:"common",lt:"O"},
{w:"onion",m:"洋葱",e:"vegetable that makes cry",l:"common",lt:"O"},
{w:"oozing",m:"渗出",e:"slowly leaking",l:"common",lt:"O"},
{w:"ordinary",m:"普通的",e:"not special",l:"common",lt:"O"},
{w:"other",m:"其他的",e:"not this one",l:"common",lt:"O"},
{w:"outback",m:"内陆",e:"wild Australian land",l:"common",lt:"O"},
{w:"outdoors",m:"户外",e:"outside",l:"common",lt:"O"},
{w:"outside",m:"外面",e:"not inside",l:"common",lt:"O"},
{w:"over",m:"在上面",e:"above",l:"common",lt:"O"},
{w:"own",m:"自己的",e:"belonging to you",l:"common",lt:"O"},
{w:"oblige",m:"帮忙",e:"to do a favour",l:"difficult",lt:"O"},
{w:"observe",m:"观察",e:"to watch carefully",l:"difficult",lt:"O"},
{w:"obviously",m:"显然",e:"clearly, easy to see",l:"difficult",lt:"O"},
{w:"occur",m:"发生",e:"to happen",l:"difficult",lt:"O"},
{w:"ogre",m:"食人魔",e:"big scary monster",l:"difficult",lt:"O"},
{w:"omit",m:"省略",e:"to leave out",l:"difficult",lt:"O"},
{w:"opportunity",m:"机会",e:"a chance",l:"difficult",lt:"O"},
{w:"opposition",m:"反对",e:"being against",l:"difficult",lt:"O"},
{w:"optical",m:"光学的",e:"about eyes or light",l:"difficult",lt:"O"},
{w:"optimist",m:"乐观者",e:"sees the good side",l:"difficult",lt:"O"},
{w:"option",m:"选项",e:"a choice",l:"difficult",lt:"O"},
{w:"organise",m:"组织",e:"to arrange, plan",l:"difficult",lt:"O"},
{w:"origami",m:"折纸",e:"paper folding art",l:"difficult",lt:"O"},
{w:"orphan",m:"孤儿",e:"child with no parents",l:"difficult",lt:"O"},
{w:"orphanage",m:"孤儿院",e:"home for orphans",l:"difficult",lt:"O"},
{w:"oxygen",m:"氧气",e:"gas we breathe",l:"difficult",lt:"O"},
{w:"obedience",m:"服从",e:"doing what you're told",l:"challenging",lt:"O"},
{w:"obnoxious",m:"讨厌的",e:"very annoying",l:"challenging",lt:"O"},
{w:"obscure",m:"模糊的",e:"hard to see or know",l:"challenging",lt:"O"},
{w:"observation",m:"观察",e:"watching carefully",l:"challenging",lt:"O"},
{w:"obsessed",m:"着迷的",e:"can't stop thinking",l:"challenging",lt:"O"},
{w:"obsessive",m:"强迫的",e:"too focused on one thing",l:"challenging",lt:"O"},
{w:"occasionally",m:"偶尔",e:"sometimes",l:"challenging",lt:"O"},
{w:"occasions",m:"场合",e:"special times",l:"challenging",lt:"O"},
{w:"occurrence",m:"事件",e:"something that happens",l:"challenging",lt:"O"},
{w:"opaque",m:"不透明的",e:"can't see through",l:"challenging",lt:"O"},
{w:"oscillate",m:"振荡",e:"swing back and forth",l:"challenging",lt:"O"},
{w:"park",m:"公园",e:"place to play outside",l:"simple",lt:"P"},
{w:"pay",m:"付钱",e:"give money for",l:"simple",lt:"P"},
{w:"pen",m:"笔",e:"write with it",l:"simple",lt:"P"},
{w:"play",m:"玩",e:"have fun",l:"simple",lt:"P"},
{w:"plot",m:"情节",e:"story plan",l:"simple",lt:"P"},
{w:"pull",m:"拉",e:"drag toward you",l:"simple",lt:"P"},
{w:"put",m:"放",e:"place somewhere",l:"simple",lt:"P"},
{w:"pair",m:"一对",e:"two together",l:"common",lt:"P"},
{w:"panic",m:"恐慌",e:"sudden fear",l:"common",lt:"P"},
{w:"parents",m:"父母",e:"mum and dad",l:"common",lt:"P"},
{w:"patter",m:"啪嗒声",e:"light tapping sound",l:"common",lt:"P"},
{w:"paw",m:"爪子",e:"animal's foot",l:"common",lt:"P"},
{w:"people",m:"人们",e:"men, women, children",l:"common",lt:"P"},
{w:"perfect",m:"完美的",e:"no mistakes",l:"common",lt:"P"},
{w:"phone",m:"电话",e:"call people with it",l:"common",lt:"P"},
{w:"picture",m:"图片",e:"image to look at",l:"common",lt:"P"},
{w:"pirate",m:"海盗",e:"steals on the sea",l:"common",lt:"P"},
{w:"place",m:"地方",e:"a spot, location",l:"common",lt:"P"},
{w:"planet",m:"星球",e:"world in space",l:"common",lt:"P"},
{w:"plastic",m:"塑料",e:"man-made material",l:"common",lt:"P"},
{w:"platform",m:"平台",e:"raised flat area",l:"common",lt:"P"},
{w:"police",m:"警察",e:"keep people safe",l:"common",lt:"P"},
{w:"poor",m:"穷的",e:"not much money",l:"common",lt:"P"},
{w:"potatoes",m:"土豆",e:"vegetable underground",l:"common",lt:"P"},
{w:"power",m:"力量",e:"strength, energy",l:"common",lt:"P"},
{w:"pretty",m:"漂亮的",e:"nice to look at",l:"common",lt:"P"},
{w:"princess",m:"公主",e:"king's daughter",l:"common",lt:"P"},
{w:"problem",m:"问题",e:"something to solve",l:"common",lt:"P"},
{w:"purpose",m:"目的",e:"reason for doing",l:"common",lt:"P"},
{w:"parallel",m:"平行的",e:"same distance apart",l:"difficult",lt:"P"},
{w:"particular",m:"特定的",e:"one specific thing",l:"difficult",lt:"P"},
{w:"pedestal",m:"底座",e:"stand for statue",l:"difficult",lt:"P"},
{w:"personalities",m:"个性",e:"how people act",l:"difficult",lt:"P"},
{w:"pincer",m:"钳子",e:"claw for gripping",l:"difficult",lt:"P"},
{w:"plait",m:"辫子",e:"braided hair",l:"difficult",lt:"P"},
{w:"pleasure",m:"快乐",e:"happy feeling",l:"difficult",lt:"P"},
{w:"prankster",m:"恶作剧者",e:"person who jokes",l:"difficult",lt:"P"},
{w:"pray",m:"祈祷",e:"talk to God",l:"difficult",lt:"P"},
{w:"precious",m:"珍贵的",e:"very valuable",l:"difficult",lt:"P"},
{w:"predators",m:"捕食者",e:"animals that hunt",l:"difficult",lt:"P"},
{w:"presence",m:"存在",e:"being there",l:"difficult",lt:"P"},
{w:"prey",m:"猎物",e:"animal being hunted",l:"difficult",lt:"P"},
{w:"principal",m:"校长",e:"head of school",l:"difficult",lt:"P"},
{w:"principle",m:"原则",e:"rule or belief",l:"difficult",lt:"P"},
{w:"probably",m:"可能",e:"most likely",l:"difficult",lt:"P"},
{w:"professor",m:"教授",e:"university teacher",l:"difficult",lt:"P"},
{w:"pumpkin",m:"南瓜",e:"big orange vegetable",l:"difficult",lt:"P"},
{w:"punctual",m:"准时的",e:"on time",l:"difficult",lt:"P"},
{w:"pure",m:"纯的",e:"clean, not mixed",l:"difficult",lt:"P"},
{w:"purest",m:"最纯的",e:"most clean",l:"difficult",lt:"P"},
{w:"purist",m:"纯粹主义者",e:"wants things perfect",l:"difficult",lt:"P"},
{w:"pursuit",m:"追求",e:"chasing after",l:"difficult",lt:"P"},
{w:"peculiar",m:"奇特的",e:"strange, odd",l:"challenging",lt:"P"},
{w:"personally",m:"亲自",e:"by yourself",l:"challenging",lt:"P"},
{w:"persuade",m:"说服",e:"talk into doing",l:"challenging",lt:"P"},
{w:"persuasive",m:"有说服力",e:"good at convincing",l:"challenging",lt:"P"},
{w:"pessimistic",m:"悲观的",e:"expecting the worst",l:"challenging",lt:"P"},
{w:"phosphorescent",m:"磷光的",e:"glows in the dark",l:"challenging",lt:"P"},
{w:"physically",m:"身体上",e:"about the body",l:"challenging",lt:"P"},
{w:"plateau",m:"高原",e:"flat high land",l:"challenging",lt:"P"},
{w:"population",m:"人口",e:"number of people",l:"challenging",lt:"P"},
{w:"precise",m:"精确的",e:"exact, correct",l:"challenging",lt:"P"},
{w:"prevalence",m:"普遍",e:"how common it is",l:"challenging",lt:"P"},
{w:"privileged",m:"有特权的",e:"having advantages",l:"challenging",lt:"P"},
{w:"proposition",m:"提议",e:"an offer or idea",l:"challenging",lt:"P"},
{w:"psychiatrist",m:"精神科医生",e:"mind doctor",l:"challenging",lt:"P"},
{w:"psychic",m:"通灵的",e:"reads minds",l:"challenging",lt:"P"},
{w:"psychology",m:"心理学",e:"study of the mind",l:"challenging",lt:"P"},
{w:"quality",m:"质量",e:"how good it is",l:"common",lt:"Q"},
{w:"queen",m:"女王",e:"female ruler",l:"common",lt:"Q"},
{w:"question",m:"问题",e:"ask to find out",l:"common",lt:"Q"},
{w:"quick",m:"快的",e:"fast",l:"common",lt:"Q"},
{w:"quickened",m:"加快了",e:"got faster",l:"common",lt:"Q"},
{w:"quickly",m:"快地",e:"in a fast way",l:"common",lt:"Q"},
{w:"quiet",m:"安静的",e:"not loud",l:"common",lt:"Q"},
{w:"quite",m:"相当",e:"fairly, pretty much",l:"common",lt:"Q"},
{w:"quaint",m:"古雅的",e:"old and charming",l:"difficult",lt:"Q"},
{w:"quay",m:"码头",e:"place boats stop",l:"difficult",lt:"Q"},
{w:"quench",m:"解渴",e:"satisfy thirst",l:"difficult",lt:"Q"},
{w:"query",m:"疑问",e:"a question",l:"difficult",lt:"Q"},
{w:"queue",m:"排队",e:"line of people waiting",l:"difficult",lt:"Q"},
{w:"quiescent",m:"静止的",e:"still, not moving",l:"challenging",lt:"Q"},
{w:"ran",m:"跑了",e:"past tense of run",l:"simple",lt:"R"},
{w:"red",m:"红色",e:"colour of blood",l:"simple",lt:"R"},
{w:"rest",m:"休息",e:"to relax",l:"simple",lt:"R"},
{w:"roof",m:"屋顶",e:"top of building",l:"simple",lt:"R"},
{w:"room",m:"房间",e:"space in a house",l:"simple",lt:"R"},
{w:"rot",m:"腐烂",e:"to go bad",l:"simple",lt:"R"},
{w:"run",m:"跑",e:"to move fast",l:"simple",lt:"R"},
{w:"rain",m:"雨",e:"water from sky",l:"common",lt:"R"},
{w:"rainbow",m:"彩虹",e:"colourful arc in sky",l:"common",lt:"R"},
{w:"rainforest",m:"雨林",e:"wet thick forest",l:"common",lt:"R"},
{w:"readers",m:"读者",e:"people who read",l:"common",lt:"R"},
{w:"realise",m:"意识到",e:"to understand",l:"common",lt:"R"},
{w:"really",m:"真的",e:"truly",l:"common",lt:"R"},
{w:"recover",m:"恢复",e:"to get better",l:"common",lt:"R"},
{w:"reflect",m:"反射",e:"bounce light back",l:"common",lt:"R"},
{w:"region",m:"地区",e:"area of land",l:"common",lt:"R"},
{w:"remember",m:"记住",e:"not forget",l:"common",lt:"R"},
{w:"report",m:"报告",e:"tell what happened",l:"common",lt:"R"},
{w:"reptile",m:"爬行动物",e:"snake, lizard etc.",l:"common",lt:"R"},
{w:"rescued",m:"救了",e:"saved from danger",l:"common",lt:"R"},
{w:"results",m:"结果",e:"what happened",l:"common",lt:"R"},
{w:"return",m:"返回",e:"to come back",l:"common",lt:"R"},
{w:"revenge",m:"报仇",e:"getting back at",l:"common",lt:"R"},
{w:"riot",m:"暴乱",e:"angry crowd fight",l:"common",lt:"R"},
{w:"ripple",m:"涟漪",e:"small wave",l:"common",lt:"R"},
{w:"roar",m:"吼叫",e:"loud animal sound",l:"common",lt:"R"},
{w:"robot",m:"机器人",e:"machine that works",l:"common",lt:"R"},
{w:"rodent",m:"啮齿动物",e:"mouse, rat etc.",l:"common",lt:"R"},
{w:"rude",m:"粗鲁的",e:"not polite",l:"common",lt:"R"},
{w:"rumble",m:"隆隆声",e:"low rolling sound",l:"common",lt:"R"},
{w:"running",m:"跑步",e:"moving fast",l:"common",lt:"R"},
{w:"radial",m:"辐射的",e:"from the centre out",l:"difficult",lt:"R"},
{w:"ravine",m:"峡谷",e:"deep narrow valley",l:"difficult",lt:"R"},
{w:"razor",m:"剃刀",e:"sharp blade",l:"difficult",lt:"R"},
{w:"realistic",m:"现实的",e:"like real life",l:"difficult",lt:"R"},
{w:"receive",m:"收到",e:"to get something",l:"difficult",lt:"R"},
{w:"recent",m:"最近的",e:"not long ago",l:"difficult",lt:"R"},
{w:"recognise",m:"认出",e:"to know who it is",l:"difficult",lt:"R"},
{w:"recommend",m:"推荐",e:"to suggest",l:"difficult",lt:"R"},
{w:"rectangular",m:"长方形的",e:"rectangle shaped",l:"difficult",lt:"R"},
{w:"relationships",m:"关系",e:"connections",l:"difficult",lt:"R"},
{w:"relevant",m:"相关的",e:"matters, important",l:"difficult",lt:"R"},
{w:"reliving",m:"重温",e:"living again",l:"difficult",lt:"R"},
{w:"reluctant",m:"不情愿的",e:"don't want to",l:"difficult",lt:"R"},
{w:"remnant",m:"残余",e:"leftover piece",l:"difficult",lt:"R"},
{w:"remorse",m:"悔恨",e:"feeling very sorry",l:"difficult",lt:"R"},
{w:"replenish",m:"补充",e:"fill up again",l:"difficult",lt:"R"},
{w:"require",m:"需要",e:"to need",l:"difficult",lt:"R"},
{w:"resources",m:"资源",e:"things you can use",l:"difficult",lt:"R"},
{w:"responsible",m:"负责的",e:"in charge of",l:"difficult",lt:"R"},
{w:"rhyme",m:"押韵",e:"words that sound same",l:"difficult",lt:"R"},
{w:"ridiculous",m:"荒谬的",e:"very silly",l:"difficult",lt:"R"},
{w:"rogue",m:"流氓",e:"dishonest person",l:"difficult",lt:"R"},
{w:"racquet",m:"球拍",e:"bat for tennis",l:"challenging",lt:"R"},
{w:"rancour",m:"怨恨",e:"deep anger",l:"challenging",lt:"R"},
{w:"realistically",m:"现实地",e:"in a real way",l:"challenging",lt:"R"},
{w:"recognisable",m:"可识别的",e:"easy to know",l:"challenging",lt:"R"},
{w:"redemption",m:"救赎",e:"being saved",l:"challenging",lt:"R"},
{w:"reign",m:"统治",e:"rule as king/queen",l:"challenging",lt:"R"},
{w:"rein",m:"缰绳",e:"strap to control horse",l:"challenging",lt:"R"},
{w:"reminiscent",m:"令人想起",e:"makes you remember",l:"challenging",lt:"R"},
{w:"responsibility",m:"责任",e:"duty to do",l:"challenging",lt:"R"},
{w:"resurrect",m:"复活",e:"bring back to life",l:"challenging",lt:"R"},
{w:"resuscitate",m:"复苏",e:"bring back breathing",l:"challenging",lt:"R"},
{w:"rhythm",m:"节奏",e:"musical beat",l:"challenging",lt:"R"},
{w:"ricochet",m:"弹跳",e:"bounce off something",l:"challenging",lt:"R"},
{w:"rigorous",m:"严格的",e:"very strict",l:"challenging",lt:"R"},
{w:"sad",m:"伤心的",e:"not happy",l:"simple",lt:"S"},
{w:"saw",m:"看到了",e:"past tense of see",l:"simple",lt:"S"},
{w:"say",m:"说",e:"to speak words",l:"simple",lt:"S"},
{w:"see",m:"看",e:"use your eyes",l:"simple",lt:"S"},
{w:"seed",m:"种子",e:"plant grows from it",l:"simple",lt:"S"},
{w:"seem",m:"似乎",e:"looks like",l:"simple",lt:"S"},
{w:"set",m:"放置",e:"to put in place",l:"simple",lt:"S"},
{w:"she",m:"她",e:"a girl or woman",l:"simple",lt:"S"},
{w:"shed",m:"棚子",e:"small garden building",l:"simple",lt:"S"},
{w:"shop",m:"商店",e:"place to buy things",l:"simple",lt:"S"},
{w:"shut",m:"关",e:"to close",l:"simple",lt:"S"},
{w:"sing",m:"唱",e:"make music with voice",l:"simple",lt:"S"},
{w:"sit",m:"坐",e:"rest on a chair",l:"simple",lt:"S"},
{w:"six",m:"六",e:"number 6",l:"simple",lt:"S"},
{w:"slow",m:"慢的",e:"not fast",l:"simple",lt:"S"},
{w:"so",m:"所以",e:"therefore",l:"simple",lt:"S"},
{w:"spot",m:"地点",e:"a place, a dot",l:"simple",lt:"S"},
{w:"stand",m:"站",e:"be on your feet",l:"simple",lt:"S"},
{w:"sleep",m:"睡觉",e:"rest with eyes closed",l:"simple",lt:"S"},
{w:"safety",m:"安全",e:"being safe",l:"common",lt:"S"},
{w:"said",m:"说了",e:"past tense of say",l:"common",lt:"S"},
{w:"saving",m:"储蓄",e:"keeping money",l:"common",lt:"S"},
{w:"says",m:"说",e:"speaks",l:"common",lt:"S"},
{w:"scare",m:"吓",e:"to frighten",l:"common",lt:"S"},
{w:"scatter",m:"散开",e:"spread everywhere",l:"common",lt:"S"},
{w:"school",m:"学校",e:"where you learn",l:"common",lt:"S"},
{w:"science",m:"科学",e:"study of how things work",l:"common",lt:"S"},
{w:"scorch",m:"烧焦",e:"burn a little",l:"common",lt:"S"},
{w:"scrape",m:"刮",e:"rub against hard",l:"common",lt:"S"},
{w:"scream",m:"尖叫",e:"shout very loud",l:"common",lt:"S"},
{w:"second",m:"第二",e:"after first",l:"common",lt:"S"},
{w:"secret",m:"秘密",e:"hidden thing",l:"common",lt:"S"},
{w:"several",m:"几个",e:"more than two",l:"common",lt:"S"},
{w:"shaking",m:"发抖",e:"moving back and forth",l:"common",lt:"S"},
{w:"shape",m:"形状",e:"circle, square etc.",l:"common",lt:"S"},
{w:"sharp",m:"锋利的",e:"can cut",l:"common",lt:"S"},
{w:"shiny",m:"闪亮的",e:"reflects light",l:"common",lt:"S"},
{w:"shock",m:"震惊",e:"big surprise",l:"common",lt:"S"},
{w:"should",m:"应该",e:"ought to",l:"common",lt:"S"},
{w:"shout",m:"喊",e:"call out loud",l:"common",lt:"S"},
{w:"show",m:"展示",e:"let others see",l:"common",lt:"S"},
{w:"sign",m:"标志",e:"tells you something",l:"common",lt:"S"},
{w:"sitting",m:"坐着",e:"resting on chair",l:"common",lt:"S"},
{w:"sixth",m:"第六",e:"after fifth",l:"common",lt:"S"},
{w:"size",m:"大小",e:"how big it is",l:"common",lt:"S"},
{w:"sky",m:"天空",e:"above us, blue",l:"common",lt:"S"},
{w:"small",m:"小的",e:"not big",l:"common",lt:"S"},
{w:"someone",m:"某人",e:"a person",l:"common",lt:"S"},
{w:"sorts",m:"种类",e:"different types",l:"common",lt:"S"},
{w:"sound",m:"声音",e:"what you hear",l:"common",lt:"S"},
{w:"speak",m:"说话",e:"to talk",l:"common",lt:"S"},
{w:"speech",m:"演讲",e:"talk to people",l:"common",lt:"S"},
{w:"sprawl",m:"蔓延",e:"spread out wide",l:"common",lt:"S"},
{w:"station",m:"车站",e:"where trains stop",l:"common",lt:"S"},
{w:"steal",m:"偷",e:"take without asking",l:"common",lt:"S"},
{w:"stepped",m:"踩了",e:"put foot down",l:"common",lt:"S"},
{w:"stopped",m:"停了",e:"did not continue",l:"common",lt:"S"},
{w:"strange",m:"奇怪的",e:"weird, unusual",l:"common",lt:"S"},
{w:"strip",m:"条",e:"thin piece",l:"common",lt:"S"},
{w:"strong",m:"强壮的",e:"lots of power",l:"common",lt:"S"},
{w:"structure",m:"结构",e:"how it's built",l:"common",lt:"S"},
{w:"strung",m:"串了",e:"put on a string",l:"common",lt:"S"},
{w:"such",m:"这样的",e:"of that kind",l:"common",lt:"S"},
{w:"suddenly",m:"突然",e:"without warning",l:"common",lt:"S"},
{w:"surprise",m:"惊喜",e:"not expected",l:"common",lt:"S"},
{w:"swimming",m:"游泳",e:"moving in water",l:"common",lt:"S"},
{w:"sapphire",m:"蓝宝石",e:"blue precious stone",l:"difficult",lt:"S"},
{w:"saxophone",m:"萨克斯",e:"music instrument",l:"difficult",lt:"S"},
{w:"scavenger",m:"食腐动物",e:"finds and eats scraps",l:"difficult",lt:"S"},
{w:"scene",m:"场景",e:"part of a play",l:"difficult",lt:"S"},
{w:"sceptical",m:"怀疑的",e:"not sure it's true",l:"difficult",lt:"S"},
{w:"schnitzel",m:"炸肉排",e:"fried meat slice",l:"difficult",lt:"S"},
{w:"scientific",m:"科学的",e:"about science",l:"difficult",lt:"S"},
{w:"scissors",m:"剪刀",e:"cut paper with",l:"difficult",lt:"S"},
{w:"seize",m:"抓住",e:"grab quickly",l:"difficult",lt:"S"},
{w:"sewage",m:"污水",e:"dirty water waste",l:"difficult",lt:"S"},
{w:"sewerage",m:"下水道",e:"pipes for waste water",l:"difficult",lt:"S"},
{w:"shoulder",m:"肩膀",e:"top of arm",l:"difficult",lt:"S"},
{w:"shrieked",m:"尖叫了",e:"screamed high",l:"difficult",lt:"S"},
{w:"signal",m:"信号",e:"sign or message",l:"difficult",lt:"S"},
{w:"skeleton",m:"骨架",e:"all the bones",l:"difficult",lt:"S"},
{w:"slaughter",m:"屠杀",e:"to kill many",l:"difficult",lt:"S"},
{w:"society",m:"社会",e:"people living together",l:"difficult",lt:"S"},
{w:"sought",m:"寻找了",e:"looked for",l:"difficult",lt:"S"},
{w:"spectacular",m:"壮观的",e:"amazing to see",l:"difficult",lt:"S"},
{w:"stammered",m:"结巴了",e:"spoke with difficulty",l:"difficult",lt:"S"},
{w:"stomach",m:"胃",e:"where food goes",l:"difficult",lt:"S"},
{w:"submarine",m:"潜水艇",e:"boat under water",l:"difficult",lt:"S"},
{w:"subsided",m:"平息了",e:"calmed down",l:"difficult",lt:"S"},
{w:"success",m:"成功",e:"doing well",l:"difficult",lt:"S"},
{w:"suitable",m:"合适的",e:"right for the job",l:"difficult",lt:"S"},
{w:"summoned",m:"召唤了",e:"called to come",l:"difficult",lt:"S"},
{w:"supervision",m:"监督",e:"watching over",l:"difficult",lt:"S"},
{w:"surrounded",m:"围绕了",e:"all around",l:"difficult",lt:"S"},
{w:"survive",m:"生存",e:"stay alive",l:"difficult",lt:"S"},
{w:"system",m:"系统",e:"set of parts working",l:"difficult",lt:"S"},
{w:"sabotage",m:"破坏",e:"damage on purpose",l:"challenging",lt:"S"},
{w:"scimitar",m:"弯刀",e:"curved sword",l:"challenging",lt:"S"},
{w:"scintillate",m:"闪烁",e:"to sparkle",l:"challenging",lt:"S"},
{w:"separate",m:"分开的",e:"not together",l:"challenging",lt:"S"},
{w:"silhouette",m:"剪影",e:"dark shape outline",l:"challenging",lt:"S"},
{w:"skulduggery",m:"阴谋",e:"secret dishonest acts",l:"challenging",lt:"S"},
{w:"sovereign",m:"君主",e:"king or queen",l:"challenging",lt:"S"},
{w:"stationary",m:"静止的",e:"not moving",l:"challenging",lt:"S"},
{w:"stationery",m:"文具",e:"pens, paper (not moving)",l:"challenging",lt:"S"},
{w:"sufficient",m:"足够的",e:"enough",l:"challenging",lt:"S"},
{w:"teeth",m:"牙齿",e:"in your mouth, bite",l:"simple",lt:"T"},
{w:"tell",m:"告诉",e:"say to someone",l:"simple",lt:"T"},
{w:"tells",m:"告诉",e:"says to someone",l:"simple",lt:"T"},
{w:"ten",m:"十",e:"number 10",l:"simple",lt:"T"},
{w:"that",m:"那个",e:"the one there",l:"simple",lt:"T"},
{w:"the",m:"这/那",e:"points to something",l:"simple",lt:"T"},
{w:"then",m:"然后",e:"after that",l:"simple",lt:"T"},
{w:"thing",m:"东西",e:"an object",l:"simple",lt:"T"},
{w:"this",m:"这个",e:"the one here",l:"simple",lt:"T"},
{w:"to",m:"到",e:"toward",l:"simple",lt:"T"},
{w:"today",m:"今天",e:"this day",l:"simple",lt:"T"},
{w:"top",m:"顶部",e:"highest part",l:"simple",lt:"T"},
{w:"table",m:"桌子",e:"flat surface, legs",l:"common",lt:"T"},
{w:"tail",m:"尾巴",e:"back end of animal",l:"common",lt:"T"},
{w:"tall",m:"高的",e:"not short",l:"common",lt:"T"},
{w:"teacher",m:"老师",e:"person who teaches",l:"common",lt:"T"},
{w:"team",m:"队",e:"group working together",l:"common",lt:"T"},
{w:"their",m:"他们的",e:"belongs to them (people)",l:"common",lt:"T"},
{w:"there",m:"那里",e:"in that place (not their)",l:"common",lt:"T"},
{w:"they",m:"他们",e:"those people",l:"common",lt:"T"},
{w:"they're",m:"他们是",e:"they are",l:"common",lt:"T"},
{w:"though",m:"虽然",e:"even if",l:"common",lt:"T"},
{w:"thought",m:"想法",e:"idea in your mind",l:"common",lt:"T"},
{w:"title",m:"标题",e:"name of book/movie",l:"common",lt:"T"},
{w:"together",m:"一起",e:"with each other",l:"common",lt:"T"},
{w:"tomorrow",m:"明天",e:"the next day",l:"common",lt:"T"},
{w:"too",m:"也",e:"as well, also",l:"common",lt:"T"},
{w:"two",m:"二",e:"number 2",l:"common",lt:"T"},
{w:"touched",m:"摸了",e:"felt with hand",l:"common",lt:"T"},
{w:"tower",m:"塔",e:"tall building",l:"common",lt:"T"},
{w:"train",m:"火车",e:"rides on tracks",l:"common",lt:"T"},
{w:"travel",m:"旅行",e:"go on a trip",l:"common",lt:"T"},
{w:"treat",m:"对待",e:"act toward, a gift",l:"common",lt:"T"},
{w:"trick",m:"把戏",e:"clever plan",l:"common",lt:"T"},
{w:"tries",m:"尝试",e:"works hard to do",l:"common",lt:"T"},
{w:"trouble",m:"麻烦",e:"problem, difficulty",l:"common",lt:"T"},
{w:"taffeta",m:"塔夫绸",e:"shiny smooth cloth",l:"difficult",lt:"T"},
{w:"talons",m:"利爪",e:"bird's sharp claws",l:"difficult",lt:"T"},
{w:"tarantula",m:"狼蛛",e:"big hairy spider",l:"difficult",lt:"T"},
{w:"taught",m:"教了",e:"past tense of teach",l:"difficult",lt:"T"},
{w:"technique",m:"技巧",e:"way of doing",l:"difficult",lt:"T"},
{w:"temperature",m:"温度",e:"how hot or cold",l:"difficult",lt:"T"},
{w:"tension",m:"紧张",e:"stress, tightness",l:"difficult",lt:"T"},
{w:"tentacles",m:"触手",e:"long arms of octopus",l:"difficult",lt:"T"},
{w:"terrace",m:"露台",e:"outdoor flat area",l:"difficult",lt:"T"},
{w:"terrible",m:"糟糕的",e:"very bad",l:"difficult",lt:"T"},
{w:"terribly",m:"非常",e:"very badly",l:"difficult",lt:"T"},
{w:"terrified",m:"恐惧的",e:"very scared",l:"difficult",lt:"T"},
{w:"territory",m:"领地",e:"area of land owned",l:"difficult",lt:"T"},
{w:"thermonuclear",m:"热核的",e:"very powerful energy",l:"difficult",lt:"T"},
{w:"transfixed",m:"呆住了",e:"can't move, staring",l:"difficult",lt:"T"},
{w:"travelled",m:"旅行了",e:"went on a trip",l:"difficult",lt:"T"},
{w:"treasure",m:"宝藏",e:"valuable things",l:"difficult",lt:"T"},
{w:"telekinesis",m:"心灵感应",e:"moving things with mind",l:"challenging",lt:"T"},
{w:"temperamental",m:"喜怒无常",e:"mood changes a lot",l:"challenging",lt:"T"},
{w:"temporary",m:"临时的",e:"for a short time",l:"challenging",lt:"T"},
{w:"therapeutic",m:"治疗的",e:"helps you heal",l:"challenging",lt:"T"},
{w:"thoroughly",m:"彻底地",e:"completely",l:"challenging",lt:"T"},
{w:"tournament",m:"锦标赛",e:"competition event",l:"challenging",lt:"T"},
{w:"tsunami",m:"海啸",e:"giant ocean wave",l:"challenging",lt:"T"},
{w:"undo",m:"撤销",e:"reverse what was done",l:"simple",lt:"U"},
{w:"up",m:"上",e:"toward the sky",l:"simple",lt:"U"},
{w:"ugly",m:"丑的",e:"not nice to look at",l:"common",lt:"U"},
{w:"uncle",m:"叔叔",e:"parent's brother",l:"common",lt:"U"},
{w:"underneath",m:"下面",e:"below",l:"common",lt:"U"},
{w:"understand",m:"理解",e:"to get it",l:"common",lt:"U"},
{w:"until",m:"直到",e:"up to the time",l:"common",lt:"U"},
{w:"use",m:"使用",e:"to work with",l:"common",lt:"U"},
{w:"used",m:"用了",e:"worked with",l:"common",lt:"U"},
{w:"useful",m:"有用的",e:"helpful",l:"common",lt:"U"},
{w:"using",m:"使用",e:"working with",l:"common",lt:"U"},
{w:"usually",m:"通常",e:"most of the time",l:"common",lt:"U"},
{w:"unbelievable",m:"难以置信",e:"hard to believe",l:"difficult",lt:"U"},
{w:"uncomfortable",m:"不舒服的",e:"not cosy",l:"difficult",lt:"U"},
{w:"unexpectedly",m:"出乎意料",e:"by surprise",l:"difficult",lt:"U"},
{w:"unfortunately",m:"不幸地",e:"sadly",l:"difficult",lt:"U"},
{w:"unique",m:"独特的",e:"one of a kind",l:"difficult",lt:"U"},
{w:"unnatural",m:"不自然的",e:"not normal",l:"difficult",lt:"U"},
{w:"upholsterer",m:"装潢师",e:"fixes furniture cover",l:"difficult",lt:"U"},
{w:"urban",m:"城市的",e:"about the city",l:"difficult",lt:"U"},
{w:"urgency",m:"紧迫",e:"needing it now",l:"difficult",lt:"U"},
{w:"useless",m:"没用的",e:"not helpful",l:"difficult",lt:"U"},
{w:"ubiquitous",m:"无处不在",e:"everywhere",l:"challenging",lt:"U"},
{w:"unconscious",m:"昏迷的",e:"not awake",l:"challenging",lt:"U"},
{w:"unnecessary",m:"不必要的",e:"not needed",l:"challenging",lt:"U"},
{w:"vat",m:"大桶",e:"big container",l:"simple",lt:"V"},
{w:"vet",m:"兽医",e:"animal doctor",l:"simple",lt:"V"},
{w:"vanish",m:"消失",e:"to disappear",l:"common",lt:"V"},
{w:"very",m:"非常",e:"a lot",l:"common",lt:"V"},
{w:"view",m:"景色",e:"what you can see",l:"common",lt:"V"},
{w:"vomit",m:"呕吐",e:"throw up",l:"common",lt:"V"},
{w:"valuable",m:"有价值的",e:"worth a lot",l:"difficult",lt:"V"},
{w:"vegetation",m:"植被",e:"plants and trees",l:"difficult",lt:"V"},
{w:"verdant",m:"翠绿的",e:"green with plants",l:"difficult",lt:"V"},
{w:"vessel",m:"船",e:"large boat",l:"difficult",lt:"V"},
{w:"victory",m:"胜利",e:"winning",l:"difficult",lt:"V"},
{w:"villages",m:"村庄",e:"small towns",l:"difficult",lt:"V"},
{w:"violence",m:"暴力",e:"hurting people",l:"difficult",lt:"V"},
{w:"vision",m:"视力",e:"ability to see",l:"difficult",lt:"V"},
{w:"voyage",m:"航行",e:"long sea trip",l:"difficult",lt:"V"},
{w:"vortex",m:"漩涡",e:"spinning circle",l:"difficult",lt:"V"},
{w:"vultures",m:"秃鹫",e:"birds that eat dead",l:"difficult",lt:"V"},
{w:"vertebrates",m:"脊椎动物",e:"animals with backbone",l:"challenging",lt:"V"},
{w:"vicious",m:"凶恶的",e:"mean and cruel",l:"challenging",lt:"V"},
{w:"vulnerable",m:"脆弱的",e:"easy to hurt",l:"challenging",lt:"V"},
{w:"was",m:"是",e:"past of 'is'",l:"simple",lt:"W"},
{w:"we",m:"我们",e:"us together",l:"simple",lt:"W"},
{w:"well",m:"好",e:"in a good way",l:"simple",lt:"W"},
{w:"went",m:"去了",e:"past tense of go",l:"simple",lt:"W"},
{w:"will",m:"将",e:"going to",l:"simple",lt:"W"},
{w:"wish",m:"希望",e:"want something",l:"simple",lt:"W"},
{w:"with",m:"和",e:"together, using",l:"simple",lt:"W"},
{w:"wait",m:"等",e:"stay until ready",l:"common",lt:"W"},
{w:"walks",m:"走路",e:"moves on feet",l:"common",lt:"W"},
{w:"wall",m:"墙",e:"side of a room",l:"common",lt:"W"},
{w:"want",m:"想要",e:"wish to have",l:"common",lt:"W"},
{w:"war",m:"战争",e:"countries fighting",l:"common",lt:"W"},
{w:"warn",m:"警告",e:"tell about danger",l:"common",lt:"W"},
{w:"watch",m:"看",e:"to look at carefully",l:"common",lt:"W"},
{w:"water",m:"水",e:"clear liquid to drink",l:"common",lt:"W"},
{w:"wear",m:"穿",e:"put clothes on",l:"common",lt:"W"},
{w:"webbed",m:"有蹼的",e:"toes joined by skin",l:"common",lt:"W"},
{w:"welcome",m:"欢迎",e:"glad you came",l:"common",lt:"W"},
{w:"were",m:"是",e:"past of 'are'",l:"common",lt:"W"},
{w:"what",m:"什么",e:"asking about thing",l:"common",lt:"W"},
{w:"when",m:"什么时候",e:"at what time",l:"common",lt:"W"},
{w:"where",m:"哪里",e:"at what place",l:"common",lt:"W"},
{w:"which",m:"哪个",e:"what one",l:"common",lt:"W"},
{w:"white",m:"白色",e:"colour of snow",l:"common",lt:"W"},
{w:"who",m:"谁",e:"what person",l:"common",lt:"W"},
{w:"whole",m:"整个",e:"all of it",l:"common",lt:"W"},
{w:"whose",m:"谁的",e:"belonging to whom",l:"common",lt:"W"},
{w:"window",m:"窗户",e:"glass in wall",l:"common",lt:"W"},
{w:"wings",m:"翅膀",e:"birds fly with them",l:"common",lt:"W"},
{w:"winning",m:"赢",e:"getting the prize",l:"common",lt:"W"},
{w:"witch",m:"女巫",e:"magic woman",l:"common",lt:"W"},
{w:"without",m:"没有",e:"not having",l:"common",lt:"W"},
{w:"wizard",m:"巫师",e:"magic man",l:"common",lt:"W"},
{w:"woke",m:"醒了",e:"stopped sleeping",l:"common",lt:"W"},
{w:"woman",m:"女人",e:"adult female",l:"common",lt:"W"},
{w:"world",m:"世界",e:"the whole earth",l:"common",lt:"W"},
{w:"worried",m:"担心的",e:"feeling anxious",l:"common",lt:"W"},
{w:"would",m:"会",e:"past of 'will'",l:"common",lt:"W"},
{w:"wouldn't",m:"不会",e:"would not",l:"common",lt:"W"},
{w:"write",m:"写",e:"put words on paper",l:"common",lt:"W"},
{w:"writing",m:"写作",e:"putting words down",l:"common",lt:"W"},
{w:"wrong",m:"错的",e:"not right",l:"common",lt:"W"},
{w:"wary",m:"警惕的",e:"being careful",l:"difficult",lt:"W"},
{w:"wealthy",m:"富有的",e:"having lots of money",l:"difficult",lt:"W"},
{w:"weary",m:"疲倦的",e:"very tired",l:"difficult",lt:"W"},
{w:"wearisome",m:"令人厌烦",e:"boring, tiring",l:"difficult",lt:"W"},
{w:"weighed",m:"称了",e:"measured weight",l:"difficult",lt:"W"},
{w:"weight",m:"重量",e:"how heavy",l:"difficult",lt:"W"},
{w:"weird",m:"奇怪的",e:"strange",l:"difficult",lt:"W"},
{w:"whisper",m:"低语",e:"speak very softly",l:"difficult",lt:"W"},
{w:"wholly",m:"完全地",e:"all, completely",l:"difficult",lt:"W"},
{w:"witchery",m:"巫术",e:"magic spells",l:"difficult",lt:"W"},
{w:"women",m:"女人们",e:"more than one woman",l:"difficult",lt:"W"},
{w:"wonder",m:"想知道",e:"think about",l:"difficult",lt:"W"},
{w:"wonderful",m:"极好的",e:"very very good",l:"difficult",lt:"W"},
{w:"wrapped",m:"包裹了",e:"covered up",l:"difficult",lt:"W"},
{w:"wrinkle",m:"皱纹",e:"line on skin",l:"difficult",lt:"W"},
{w:"written",m:"写好的",e:"put in writing",l:"difficult",lt:"W"},
{w:"waive",m:"放弃",e:"give up a right",l:"challenging",lt:"W"},
{w:"wilful",m:"故意的",e:"done on purpose",l:"challenging",lt:"W"},
{w:"wondrous",m:"奇妙的",e:"amazing, wonderful",l:"challenging",lt:"W"},
{w:"wraith",m:"幽灵",e:"ghost",l:"challenging",lt:"W"},
{w:"wrought",m:"锻造的",e:"made carefully",l:"challenging",lt:"W"},
{w:"x-ray",m:"X光",e:"see inside body",l:"common",lt:"X"},
{w:"yell",m:"大叫",e:"shout loudly",l:"simple",lt:"Y"},
{w:"yes",m:"是的",e:"opposite of no",l:"simple",lt:"Y"},
{w:"you",m:"你",e:"the person spoken to",l:"simple",lt:"Y"},
{w:"yelled",m:"大叫了",e:"shouted loudly",l:"common",lt:"Y"},
{w:"yellow",m:"黄色",e:"colour of banana",l:"common",lt:"Y"},
{w:"yoke",m:"轭",e:"frame on animal's neck",l:"common",lt:"Y"},
{w:"your",m:"你的",e:"belongs to you",l:"common",lt:"Y"},
{w:"yourself",m:"你自己",e:"you alone",l:"common",lt:"Y"},
{w:"yacht",m:"游艇",e:"big fancy boat",l:"difficult",lt:"Y"},
{w:"yearn",m:"渴望",e:"want very much",l:"difficult",lt:"Y"},
{w:"yield",m:"屈服",e:"to give in",l:"difficult",lt:"Y"},
{w:"youngster",m:"年轻人",e:"young person",l:"difficult",lt:"Y"},
{w:"youthful",m:"年轻的",e:"looking young",l:"difficult",lt:"Y"},
{w:"zoo",m:"动物园",e:"place to see animals",l:"simple",lt:"Z"},
{w:"zapped",m:"击中了",e:"hit with energy",l:"common",lt:"Z"},
{w:"zany",m:"滑稽的",e:"funny and silly",l:"difficult",lt:"Z"},
{w:"zenith",m:"顶点",e:"highest point",l:"difficult",lt:"Z"},
{w:"zodiac",m:"星座",e:"star signs",l:"difficult",lt:"Z"},
{w:"zoology",m:"动物学",e:"study of animals",l:"difficult",lt:"Z"},
{w:"zephyr",m:"微风",e:"gentle breeze",l:"challenging",lt:"Z"}
];
